### ISSUE TITLE
Custom event tracker

### ISSUE THREAD

**Issue by mocheaz** [antonioribeiro/tracker#100]
When using something like this:
```
Tracker::trackEvent(['name' => 'cart.add']);
```

i'm getting this exception:
```
Call to undefined method PragmaRX\Tracker\Tracker::trackEvent()
```
This, is working fine:
```
$visitor = Tracker::currentSession();
```

**Comment by adrielzxdf** [comment]
The method 'trackEvent' is not defined in the model Tracker.php (default location I believe is in vendor/pragmarx/tracker/src/Tracker.php). Without more information, this is what I would assume the problem would be.

**Comment by mocheaz** [comment]
Thanks.

I can't find any function called trackEvent. I searched anywhere in the PragmaRX folder and everywhere in my project.

What info you need?

**Comment by adrielzxdf** [comment]
trackEvent is not defined by itself in antonioribeiro/tracker. It is an example for a custom method that you have to define yourself. 

You can define it in another model with the given example
```
Tracker::trackEvent(['name' => 'cart.add', 'object' => 'App\Cart\Events\Add']);
```
or through the routes method. At least that's what I understood from the documentation.

**Comment by mocheaz** [comment]
Sorry...

I don't see where i can define something like this.

**Comment by adrielzxdf** [comment]
Depends on where you placed your model. After Laravel 4, the Model folder is not included by default. http://laravel.io/forum/10-26-2014-laravel-5-where-is-the-models-folder

**Comment by mocheaz** [comment]
I mean, this is a specific table (tracker_events) where is the model class for this table?

**Comment by mocheaz** [comment]
I found it.
I wasn't on dev-master and this methods was added on this version only.
