### ISSUE TITLE
documentation functions are static functions but when i use it raises error can't use as static

### ISSUE THREAD

**Issue by islamdarwish** [antonioribeiro/tracker#101]
when i write : 

use PragmaRX\Tracker\Tracker;
$visitor = Tracker::currentSession();

raises error: Non-static method PragmaRX\Tracker\Tracker::currentSession() should not be called statically, assuming $this from incompatible context

how can i use it ?

**Comment by dragos090** [comment]
I have the exact same problem.. Searched no whole internet but with no result. Can someone please help with this?

**Comment by starship11** [comment]
You have imported the class here:
use PragmaRX\Tracker\Tracker;
while, you need to import the facade like:
use PragmaRX\Tracker\Vendor\Laravel\Facade as Tracker;
