### ISSUE TITLE
The example on routes by name.

### ISSUE THREAD

**Issue by kris-terziev** [antonioribeiro/tracker#103]
return Tracker::logByRouteName('user.profile')
        ->where(function($query)
        {
            $query
                ->where('parameter', 'id')
                ->where('value', 1);
        })
        ->count();

This always returns 0 for me. In fact this package doesn't write anything to the database. Not sure of the reason. Anyone?

**Comment by canfiax** [comment]
Sure you enabled the package to track route visits?
