### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation

### ISSUE THREAD

**Issue by lonerunner** [antonioribeiro/tracker#104]
I am having problems when i enable events tracking, but i don't understand why because as i checked in my database it seems that everything is alright.

```
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`perfectgamer`.`tracker_events_log`, CONSTRAINT `tracker_events_log_log_id_foreign` FOREIGN KEY (`log_id`) REFERENCES `tracker_log` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) (SQL: insert into `tracker_events_log` (`log_id`, `event_id`, `class_id`, `updated_at`, `created_at`) values (229, 4, 2, 2015-09-08 17:42:48, 2015-09-08 17:42:48))
```

**Comment by Nardusgc** [comment]
I have the same problem, did you manage to figure out what the issue was?

**Comment by pdarg** [comment]
Setting "log_events" to false in config/tracker.php works around this. Not clear what the cause is.

**Comment by antonioribeiro** [comment]
This one is tricky, looks like the event row is being created before the log row has been saved, even though $log->save() has been fired and the id generated way before event.

Thoughts?

**Comment by antonioribeiro** [comment]
Fixed.
