### ISSUE TITLE
tracker geoip/geoip is not able to find city name

### ISSUE THREAD

**Issue by simplewebteam** [antonioribeiro/tracker#105]
![screen shot 2015-09-09 at 4 37 16 pm](https://cloud.githubusercontent.com/assets/13625635/9755848/c71f0c5c-5718-11e5-9979-ec7b311438e8.png)

**Comment by lucasvrm** [comment]
I have the same problem...

**Comment by anhdt1987vn** [comment]
same problem.....

**Comment by antonioribeiro** [comment]
Yes, sometimes geoip has no access to the city name. This is problably something we would have to look in GeoIP.

FreeGeoIp also doesn't find some:

http://freegeoip.net/json/179.35.88.88

But is able to find some other:

http://freegeoip.net/json/179.35.81.88

**Comment by simplewebteam** [comment]
How do you make money out of this free package?
Or 
How do you plan to make money ?
Is it just free forever?

**Comment by antonioribeiro** [comment]
When I first created it I was already planning a big overhaul, make it faster, integrate with some other services and then make some money from it, now I'm not so sure... I think I have to give something back to the Laravel community.

**Comment by simplewebteam** [comment]
Hi Antonio

how is it going?

i just noticed tracker used to display accumulated hits on a particular IP
address as long as cookie is valid or session is alive.

since your last update, i am now getting each page view treated and
displayed as a new hit even if its same session.

can you advice?

thanks
