### ISSUE TITLE
Can't track error: code and message seem to be wrong

### ISSUE THREAD

**Issue by Pitiome** [antonioribeiro/tracker#106]
Hi!
First of all, congratulations for this package which is truly amazing! I use it for my 5.1 laravel app and it works just fine, well almost fine...
I'm having some problems to track errors, in the tracker_error table I have the following:
![phpmyadmin](https://cloud.githubusercontent.com/assets/14269535/9848726/fca63502-5ae3-11e5-97a4-75899d07ac7e.png)
On the picture you can see errors are correctly tracked but the codes corresponds to nothing. Second, all the http exceptions give the error on the line 3 : code 0 and empty message!
I checked my handler file but the http errors are configured to be reported.

I definitely thought it came from my app but to be sure I installed a fresh install of laravel and then install the tracker package. I finally tried to generate a 404 exception just to try, and surprisingly it reported exactly the same thing : code 0 and empty message!

Either I install the package wrong or the configuration I did is bad!

I looked at some files but didn't manage to find anything wrong... obviously I'm watching at the wrong place...
If you need any piece of code or some information please ask me!
Thanks!

**Comment by Nardusgc** [comment]
Hi, did find a solution for this issue?

**Comment by Pitiome** [comment]
Hi!
I haven't found any solution to this issue so far...
Have you?

**Comment by Nardusgc** [comment]
No unfortunately not, all tho I have not looked at it in depth yet. Will let you know if I find anything when I get to it again :-)

**Comment by antonioribeiro** [comment]
Unfortunatelly this is what I get from Laravel:

![](http://i.imgur.com/P4FoyWs.png)

Code = 0
Message = ''

But looks like there is something else we can use there, at least for code...

**Comment by antonioribeiro** [comment]
Fixed on master.
