### ISSUE TITLE
I got an error while running a raw query in my application..SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; 

### ISSUE THREAD

**Issue by riasat97** [antonioribeiro/tracker#110]
I found that while saving the query as statement for some reason it breaks.. so i had to use $sqlQuery = htmlentities($query['query']);  in logQuery($query) function which exists in SqlQuery.php repository... I hope author will fix it in update...

**Comment by antonioribeiro** [comment]
Done.
