### ISSUE TITLE
ErrorException in RepositoryManager.php line 262: Trying to get property of non-object

### ISSUE THREAD

**Issue by doncadavona** [antonioribeiro/tracker#112]
On my fresh Laravel 5.1 app, I just installed tracker, migrated its database and enabled the basics, basically followed the installation manual, I get this error exception when I visit any of my app's route (example: http://localhost:8000/; http://localhost:8000/admin; http://localhost:8000/profile):

ErrorException in RepositoryManager.php line 262: Trying to get property of non-object

![fireshot capture 9 - - http___localhost_8000_](https://cloud.githubusercontent.com/assets/8132015/10355352/5eea1e6a-6d9d-11e5-8b95-2c6dcb301412.png)

**Comment by antonioribeiro** [comment]
Coded some try-catch to protect from this to happen.
