### ISSUE TITLE
[ErrorException] session_start(): Cannot send session cookie

### ISSUE THREAD

**Issue by doncadavona** [antonioribeiro/tracker#113]
After installing tracker on my fresh Laravel 5.1 app, whenever I perform any **php artisan** command, I get this error:

`[ErrorException]                                                                                                      
  session_start(): Cannot send session cookie - headers already sent by (output started at /<path_to_my_laravel_app>/app/Http/routes.php:1)`

I've also performed the following undocumented installation step:

`php artisan tracker:updateparser`

*here's a screenshot*

![screen-shot-2015-10-08-at-11 48 34-am](https://cloud.githubusercontent.com/assets/8132015/10357291/07fb88da-6db3-11e5-98d0-9a4434923b14.jpg)

**Comment by antonioribeiro** [comment]
Something else in your code was doing that.
