### ISSUE TITLE
How to get user devices?

### ISSUE THREAD

**Issue by doncadavona** [antonioribeiro/tracker#114]
In the doc, it said you can track user devices. Counting user devices would equals to getting the number of unique visitors for the site, but how to actually get user devices using the Tracker Helper?

Maybe something like:

`$uniqueVisitors = Tracker::userDevices();`

`// display count of unique visitors:`
`{{ $uniqueVisitors->count() }}`

**Comment by antonioribeiro** [comment]
Added to master. Will be on 2.0.

**Comment by doncadavona** [comment]
Thanks!
