### ISSUE TITLE
Referer info doesn't contain in tracker_log

### ISSUE THREAD

**Issue by drtzack** [antonioribeiro/tracker#115]
I think it's better to keep referer info also in tracker_log.

referer changes in tracker_sessions while user surfing in the website.

**Comment by drtzack** [comment]
I'm extending the class to add that feature and some features that I need. But you defined some functions as private so I can't access them. It could be good if you change them to protected.

**Comment by antonioribeiro** [comment]
Could you tell me which ones?
Could you send a pull request to fullfull this?

**Comment by antonioribeiro** [comment]
Added referer to log.
Made everything protected.

**Comment by tokkerbaz** [comment]
i have same issue here, @antonioribeiro please help me to solve it. Referer is changing by pressing refresh button. It turns to self domain name. Not properly, rarely, it writes right referer. Where probably i should work on files?
