### ISSUE TITLE
 Jenssegers/agent added isPhone() support, breaks Tracker isPhone()

### ISSUE THREAD

**Issue by EmielBlonk** [antonioribeiro/tracker#117]
It seems [jenssegers/agent](https://github.com/jenssegers/agent) added isPhone() support and the following occurs after a composer update:

>Declaration of PragmaRX\\Tracker\\Support\\MobileDetect::isPhone() should be compatible with Jenssegers\\Agent\\Agent::isPhone($userAgent = NULL, $httpHeaders = NULL)

My current solution is to add: "jenssegers/agent": "2.1.*" to your own composer file. New functionality is from version 2.2.2 it seems.

Is there going to be an update implementing the new version of [jenssegers/agent](https://github.com/jenssegers/agent)?

**Comment by nuukcillo** [comment]
Hey, I have the same issue, however this project seems abandoned. It hasn´t been updated  in 5 months.

**Comment by EmielBlonk** [comment]
It seems that way, that's why a "fix" to this problem is to add the previous version "jenssegers/agent": "2.1.*" after  "pragmarx/tracker" in your own composer.json.

If you still get the same error message will trying to do composer update, try:

> composer update --no-scripts

After that you can run it as you always do.

**Comment by nuukcillo** [comment]
I did it before writing my previous comment, but i am kind of dissapointed because i really like this project that seems no longer supported.

**Comment by Nardusgc** [comment]
Yeah its a shame, I like this project as well. Thanks for the info on fixing this tho.

**Comment by RokSiEu** [comment]
At the moment, the best fix is to open 
 ```
Jenssegers\Agent 
```
and change line 262 
from 
```
public function isPhone($userAgent = null, $httpHeaders = null)
```
to
```
public function isPhone()
```

**Comment by matyhaty** [comment]
Also agree, the fix is this:

in /tracker/src/Support/MobileDetect.php

change:

public function isPhone()

to

public function isPhone($userAgent = NULL, $httpHeaders = NULL)

**Comment by zawzawzaw** [comment]
Thanks guys adding "jenssegers/agent": "2.1.*" to my own composer works for me

**Comment by doncadavona** [comment]
This worked for me too:
`composer require jenssegers/agent:2.1.*`
Hoping for better fix.

**Comment by ibnuhalimm** [comment]
me too, with <b> "jenssegers/agent": "2.1.*" </b>
thanks guys

**Comment by antonioribeiro** [comment]
Fixed.
