### ISSUE TITLE
Enabling log event giving sql error

### ISSUE THREAD

**Issue by raksbisht** [antonioribeiro/tracker#118]
When I am doing ,	'log_events' => true, in tracker.php ,its giving me below error.

QueryException in Connection.php line 651:
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`tracker`.`tracker_events_log`, CONSTRAINT `tracker_events_log_log_id_foreign` FOREIGN KEY (`log_id`) REFERENCES `tracker_log` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) (SQL: insert into `tracker_events_log` (`log_id`, `event_id`, `class_id`, `updated_at`, `created_at`) values (52, 4, 2, 2015-10-29 20:07:26, 2015-10-29 20:07:26))

PDOException in Connection.php line 390:
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`tracker`.`tracker_events_log`, CONSTRAINT `tracker_events_log_log_id_foreign` FOREIGN KEY (`log_id`) REFERENCES `tracker_log` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)

**Comment by antonioribeiro** [comment]
Closing in favor of: https://github.com/antonioribeiro/tracker/issues/104
