### ISSUE TITLE
tracker GeoIp/GeoIp can't locate the city 

### ISSUE THREAD

**Issue by simplewebteam** [antonioribeiro/tracker#120]
![screen shot 2015-11-15 at 10 25 26 pm](https://cloud.githubusercontent.com/assets/13625635/11168558/d2d19f02-8be7-11e5-87ed-02a4198cb203.png)

**Comment by antonioribeiro** [comment]
This is a problem in the geoip/geoip package, sometimes it cannot get the city, happens with me too. I suggest you to talk with them.
