### ISSUE TITLE
faceing problem with datatable

### ISSUE THREAD

**Issue by s1rxploit** [antonioribeiro/tracker#122]
http://prntscr.com/953gco
i use https://github.com/Chumper/Datatable
for my site .when i add tracker then i face the problem. in stats panel datatable working . but in my site route where i call Chumper/Datatable its showing the problem. otherwise everything ok.
but class file are not same then why i get the problem?
any idea ?
really i want to use tracker. but i can not also change   Chumper/Datatable coz i allready write huge code :s

**Comment by antonioribeiro** [comment]
Sorry, buddy, I really have no idea, looks like you have a class conflict, table() method is being called on Datatables when it shouldn't.
