### ISSUE TITLE
There are no commands defined in the "tracker" namespace. 

### ISSUE THREAD

**Issue by simplewebteam** [antonioribeiro/tracker#123]

**Comment by antonioribeiro** [comment]
Are you trying to run php artisan tracker:tables?

**Comment by simplewebteam** [comment]
Php artisan tracker:updateparser

**Comment by antonioribeiro** [comment]
There is no need to execute tracker:updateparser during install anymore.

**Comment by Cope84** [comment]
I am trying to do so, but I am not able to.
