### ISSUE TITLE
[RuntimeException]

### ISSUE THREAD

**Issue by simplewebteam** [antonioribeiro/tracker#124]
php artisan optimize --force generates this
 [RuntimeException]                                                                                                                                        Error Output: PHP Fatal error:  Class 'PragmaRX\Support\GeoIp' not found in /Users/RAJ2014/code/SosApp50/vendor/pragmarx/tracker/src/Vendor/Laravel/ServiceProvider.php on line 252

**Comment by antonioribeiro** [comment]
I just tagged a new version, should be fixed now.
