### ISSUE TITLE
Class 'PragmaRX\Support\GeoIp\GeoIp' not found

### ISSUE THREAD

**Issue by dcnl1980** [antonioribeiro/tracker#125]
After installing the package with composer we get the following error:

Error Output: PHP Fatal error:  Class 'PragmaRX\Support\GeoIp\GeoIp' not found in /srv/www/laravel/vendor/pragmarx/tracker/src/Vendor/Laravel/ServiceProvider.php on line 252

We tried to install GeoIP2 but it's not helping.

**Comment by dcnl1980** [comment]
I'm using Laravel 4 (latest)

**Comment by dcnl1980** [comment]
Directory is not case sensitive. Please pull this issue to the branche:

mv vendor/pragmarx/support/src/geoip vendor/pragmarx/support/src/GeoIp

**Comment by doncadavona** [comment]
Still not fixed after renaming vendor/pragmarx/support/src/geoip to vendor/pragmarx/support/src/GeoIp.
Class 'PragmaRX\Support\GeoIp\GeoIp' still not found afterwards.
