### ISSUE TITLE
PHP 5.5 requirement

### ISSUE THREAD

**Issue by rutgernation** [antonioribeiro/tracker#126]
The Requirements state it is possible to install this package on PHP 5.4.*, but I think one needs PHP 5.5 to prevent getting the "syntax error, unexpected 'class'" error on config/config.php on line 208.

https://github.com/antonioribeiro/tracker/blob/master/src/config/config.php (line 208)

I'm using PHP 5.4.12.

**Comment by antonioribeiro** [comment]
You're right. Thank you!
