### ISSUE TITLE
Class 'PragmaRX\Support\GeoIp\GeoIp' not found

### ISSUE THREAD

**Issue by doncadavona** [antonioribeiro/tracker#129]
Just updated to version 2.0.0. Upon executing php artisan tracker:tables, this error occurs:

Class 'PragmaRX\Support\GeoIp\GeoIp' not found.

**Comment by doncadavona** [comment]
Still not fixed after renaming vendor/pragmarx/support/src/geoip to vendor/pragmarx/support/src/GeoIp.
Class 'PragmaRX\Support\GeoIp\GeoIp' still not found afterwards.

**Comment by doncadavona** [comment]
Got it working by moving **pragmarx\support\src\GeoIp.php** to **pragmarx\support\src\GeoIp\GeoIp.php** then updating it's namespace from

`namespace PragmaRX\Support;`

`namespace PragmaRX\Support\GeoIp;`

### BUT,

A new issue on migrating the tables came on `php artisan migrate`:

 `[Illuminate\Database\QueryException]                                         
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydatabase.t  
  racker_referers' doesn't exist (SQL: SQLSTATE[42S02]: Base table or view no  
  t found: 1146 Table 'mydatabase.tracker_referers' doesn't exist (SQL: a  
  lter table `tracker_referers` add `medium` varchar(255) null, add `source`   
  varchar(255) null, add `search_terms_hash` varchar(255) null)) 
`

**Comment by rajanrawal** [comment]
Refer this ans for future reference 
[https://github.com/antonioribeiro/firewall/issues/36](https://github.com/antonioribeiro/firewall/issues/36)

**Comment by rajanrawal** [comment]
Go to `vendor\pragmarx\firewall\src\Vendor\Laravel\ServiceProvider.php` 
Near by line no 8 or so, Change 
`use PragmaRX\Support\GeoIp;`
to 
`use PragmaRX\Support\GeoIp\GeoIp;`

Then 

Go to `vendor\pragmarx\firewall\src\Firewall.php`
Near by line no 32 or so, Change 
`use PragmaRX\Support\GeoIp;`
to 
`use PragmaRX\Support\GeoIp\GeoIp;`

Should work fine then.

**Comment by antonioribeiro** [comment]
Fixed a long time ago.
