### ISSUE TITLE
GeoIp it doesnt work

### ISSUE THREAD

**Issue by infharis** [antonioribeiro/tracker#130]
tracker is very benefit, thanks
but i have a question
so information about of Geoip doesnt stored in my database,
is it need other configure?

**Comment by joaodman** [comment]
You need to install geoip and then in the configuration file set 'log_geoip' => true

**Comment by m7vm7v** [comment]
Hi, I have installed geoIP1 and geoIP2 and enabled it in the config but still have the message:
Trying to get property of non-object
