### ISSUE TITLE
i cant get pageviews ?

### ISSUE THREAD

**Issue by oguzcicek** [antonioribeiro/tracker#131]
i installed everything , but i can't get pageviews.
which log options should i change from config/tracker.php to get post's page views ? ( all of them false now ) should i activate logs to get page views ?
what i want to do is getting posts's page views.. 
it always display 0 to me.  i'm working on my local , i deleted 'do_not_track_ips' 

my code : 
Routes
```
Route::get('blog/{slug}', ['as' => 'blog.show', 'uses' => 'Frontend\BlogController@show']);
```
blogcontroller
```

	public function show($slug)
	{
		//
		$post = $this->blogRepo->getBySlug($slug);
		$pageViews= \Tracker::logByRouteName('blog.show')
				->where(function($query)
				{
					$query
							->where('parameter', 'slug')
							->where('value', '$slug');
				})
				->count();

		return view('frontend.blog-post' , compact('post'  , 'pageViews' ));
	}
 
```
view 

```
      <p class="post-views"> {{ $pageViews  }}</p>
```

**Comment by simplewebteam** [comment]
$query
                            ->where('parameter', 'slug')
                            ->where('value', '$slug');

shouldn't you be using ->where('value', $slug);

**Comment by oguzcicek** [comment]
its not working , its always shows 0 . should i activate logs to see page views ? 
or can i use it without logs ?

**Comment by joaodman** [comment]
I think logs must be enabled in order for the page views to be saved to your database from where they can be read. I get pageviews when I set log_enabled to true in the options.

**Comment by adehazril** [comment]
I'm getting the same problem. Have you solved this, @oguzcicek ?

**Comment by diegorodriguezvidal** [comment]
Some error here, did you solve the problem? @oguzcicek @adehazril

**Comment by adehazril** [comment]
@diegorodriguezvidal unfortunately not. Decided to just make the pageview tracker myself.

**Comment by tornadofay** [comment]
is there any work around for this bug ?

**Comment by tornadofay** [comment]
Well here is solution the syntax of this method is wrong here is the right way to do it:
I give example from my code which is working for me.

Controller:
```
public function show(Post $post)
    {    
      $pageViews = \Tracker::logByRouteName('posts.show')
            ->where(function($query) **use ($post)**
            {
                $query
                    ->where('parameter', 'id')
                    ->where('value', $post->id);
            })
            ->select('tracker_log.session_id')
            ->groupBy('tracker_log.session_id')
            ->distinct()
            ->count('tracker_log.session_id');
```
Notice the **use ($post)** after **->where(function($query)**, I bold the missing syntax. 
the problem was pass the necessary variables from the parent scope into the closure with the use keyword.
credits for this post helped me to spot the syntax error : [https://stackoverflow.com/questions/29548073/laravel-advanced-wheres-how-to-pass-variable-into-function](url)

hope it helps.

**Comment by tornadofay** [comment]
I found work around this bug, 
```
public function show($slug){
        $pageViews = DB::select("select count(distinct `tracker_log`.`session_id`) as aggregate 
                    from `YourTrackerDatabaseName`.`tracker_log`
                    inner join `YourTrackerDatabaseName`.`tracker_route_paths` on `tracker_route_paths`.`id` = `tracker_log`.`route_path_id` 
                    left join `YourTrackerDatabaseName`.`tracker_route_path_parameters` on `tracker_route_path_parameters`.`route_path_id` = `tracker_route_paths`.`id` 
                    inner join `YourTrackerDatabaseName`.`tracker_routes` on `tracker_routes`.`id` = `tracker_route_paths`.`route_id` 
                    where `tracker_route_paths`.`path` = 'posts/". $slug ."'");

return view('post.show',compact('pageViews'));
}
```
Then on Blade view we can do this
`<i class="fas fa-eye">&nbsp;{{$pageViews[0]->aggregate}}</i>`
OR
`{{$pageViews[0]->aggregate}}`
