### ISSUE TITLE
Installation request for symfony/yaml

### ISSUE THREAD

**Issue by ghost** [antonioribeiro/tracker#132]
I got this error when I tried to install it. I am using laravel 5.1
C:\xampp\htdocs\mpms>composer require pragmarx/tracker
Using version ^2.0 for pragmarx/tracker
./composer.json has been updated
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for pragmarx/tracker ^2.0 -> satisfiable by pragmarx
tracker[v2.0.0].
    - Conclusion: remove symfony/yaml v3.0.0
    - Conclusion: don't install symfony/yaml v3.0.0
    - pragmarx/tracker v2.0.0 requires ua-parser/uap-php ~3.4 -> satisfiable by
ua-parser/uap-php[v3.4.0, v3.4.1, v3.4.2, v3.4.3, v3.4.4].
    - ua-parser/uap-php v3.4.0 requires symfony/yaml ~2 -> satisfiable by symfo
y/yaml[2.0.4, 2.0.5, 2.0.6, 2.0.7, v2.0.10, v2.0.12, v2.0.13, v2.0.14, v2.0.15,
v2.0.16, v2.0.17, v2.0.18, v2.0.19, v2.0.20, v2.0.21, v2.0.22, v2.0.23, v2.0.24
 v2.0.25, v2.0.9, v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v
.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10,
2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0,
v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17,
v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25,
v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33,
v2.3.34, v2.3.35, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.
, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5
0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v
.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.2, v2.6.3
 v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3
 v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.8.0].
    - ua-parser/uap-php v3.4.1 requires symfony/yaml ~2 -> satisfiable by symfo
y/yaml[2.0.4, 2.0.5, 2.0.6, 2.0.7, v2.0.10, v2.0.12, v2.0.13, v2.0.14, v2.0.15,
v2.0.16, v2.0.17, v2.0.18, v2.0.19, v2.0.20, v2.0.21, v2.0.22, v2.0.23, v2.0.24
 v2.0.25, v2.0.9, v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v
.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10,
2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0,
v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17,
v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25,
v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33,
v2.3.34, v2.3.35, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.
, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5
0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v
.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.2, v2.6.3
 v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3
 v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.8.0].
    - ua-parser/uap-php v3.4.2 requires symfony/yaml ~2 -> satisfiable by symfo
y/yaml[2.0.4, 2.0.5, 2.0.6, 2.0.7, v2.0.10, v2.0.12, v2.0.13, v2.0.14, v2.0.15,
v2.0.16, v2.0.17, v2.0.18, v2.0.19, v2.0.20, v2.0.21, v2.0.22, v2.0.23, v2.0.24
 v2.0.25, v2.0.9, v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v
.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10,
2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0,
v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17,
v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25,
v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33,
v2.3.34, v2.3.35, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.
, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5
0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v
.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.2, v2.6.3
 v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3
 v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.8.0].
    - ua-parser/uap-php v3.4.3 requires symfony/yaml ~2 -> satisfiable by symfo
y/yaml[2.0.4, 2.0.5, 2.0.6, 2.0.7, v2.0.10, v2.0.12, v2.0.13, v2.0.14, v2.0.15,
v2.0.16, v2.0.17, v2.0.18, v2.0.19, v2.0.20, v2.0.21, v2.0.22, v2.0.23, v2.0.24
 v2.0.25, v2.0.9, v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v
.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10,
2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0,
v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17,
v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25,
v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33,
v2.3.34, v2.3.35, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.
, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5
0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v
.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.2, v2.6.3
 v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3
 v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.8.0].
    - ua-parser/uap-php v3.4.4 requires symfony/yaml ~2 -> satisfiable by symfo
y/yaml[2.0.4, 2.0.5, 2.0.6, 2.0.7, v2.0.10, v2.0.12, v2.0.13, v2.0.14, v2.0.15,
v2.0.16, v2.0.17, v2.0.18, v2.0.19, v2.0.20, v2.0.21, v2.0.22, v2.0.23, v2.0.24
 v2.0.25, v2.0.9, v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v
.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10,
2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0,
v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17,
v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25,
v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33,
v2.3.34, v2.3.35, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.
, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5
0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v
.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.2, v2.6.3
 v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3
 v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.8.0].
    - Can only install one of: symfony/yaml[v2.1.0, v3.0.0].
    - Can only install one of: symfony/yaml[v2.1.1, v3.0.0].
    - Can only install one of: symfony/yaml[v2.1.10, v3.0.0].
    - Can only install one of: symfony/yaml[v2.1.11, v3.0.0].
    - Can only install one of: symfony/yaml[v2.1.12, v3.0.0].
    - Can only install one of: symfony/yaml[v2.1.13, v3.0.0].
    - Can only install one of: symfony/yaml[v2.1.2, v3.0.0].
    - Can only install one of: symfony/yaml[v2.1.3, v3.0.0].
    - Can only install one of: symfony/yaml[v2.1.4, v3.0.0].
    - Can only install one of: symfony/yaml[v2.1.5, v3.0.0].
    - Can only install one of: symfony/yaml[v2.1.6, v3.0.0].
    - Can only install one of: symfony/yaml[v2.1.7, v3.0.0].
    - Can only install one of: symfony/yaml[v2.1.8, v3.0.0].
    - Can only install one of: symfony/yaml[v2.1.9, v3.0.0].
    - Can only install one of: symfony/yaml[v2.2.0, v3.0.0].
    - Can only install one of: symfony/yaml[v2.2.1, v3.0.0].
    - Can only install one of: symfony/yaml[v2.2.10, v3.0.0].
    - Can only install one of: symfony/yaml[v2.2.11, v3.0.0].
    - Can only install one of: symfony/yaml[v2.2.2, v3.0.0].
    - Can only install one of: symfony/yaml[v2.2.3, v3.0.0].
    - Can only install one of: symfony/yaml[v2.2.4, v3.0.0].
    - Can only install one of: symfony/yaml[v2.2.5, v3.0.0].
    - Can only install one of: symfony/yaml[v2.2.6, v3.0.0].
    - Can only install one of: symfony/yaml[v2.2.7, v3.0.0].
    - Can only install one of: symfony/yaml[v2.2.8, v3.0.0].
    - Can only install one of: symfony/yaml[v2.2.9, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.0, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.1, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.10, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.11, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.12, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.13, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.14, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.15, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.16, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.17, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.18, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.19, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.2, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.20, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.21, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.22, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.23, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.24, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.25, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.26, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.27, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.28, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.29, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.3, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.30, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.31, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.32, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.33, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.34, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.35, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.4, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.5, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.6, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.7, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.8, v3.0.0].
    - Can only install one of: symfony/yaml[v2.3.9, v3.0.0].
    - Can only install one of: symfony/yaml[v2.4.0, v3.0.0].
    - Can only install one of: symfony/yaml[v2.4.1, v3.0.0].
    - Can only install one of: symfony/yaml[v2.4.10, v3.0.0].
    - Can only install one of: symfony/yaml[v2.4.2, v3.0.0].
    - Can only install one of: symfony/yaml[v2.4.3, v3.0.0].
    - Can only install one of: symfony/yaml[v2.4.4, v3.0.0].
    - Can only install one of: symfony/yaml[v2.4.5, v3.0.0].
    - Can only install one of: symfony/yaml[v2.4.6, v3.0.0].
    - Can only install one of: symfony/yaml[v2.4.7, v3.0.0].
    - Can only install one of: symfony/yaml[v2.4.8, v3.0.0].
    - Can only install one of: symfony/yaml[v2.4.9, v3.0.0].
    - Can only install one of: symfony/yaml[v2.5.0, v3.0.0].
    - Can only install one of: symfony/yaml[v2.5.1, v3.0.0].
    - Can only install one of: symfony/yaml[v2.5.10, v3.0.0].
    - Can only install one of: symfony/yaml[v2.5.11, v3.0.0].
    - Can only install one of: symfony/yaml[v2.5.12, v3.0.0].
    - Can only install one of: symfony/yaml[v2.5.2, v3.0.0].
    - Can only install one of: symfony/yaml[v2.5.3, v3.0.0].
    - Can only install one of: symfony/yaml[v2.5.4, v3.0.0].
    - Can only install one of: symfony/yaml[v2.5.5, v3.0.0].
    - Can only install one of: symfony/yaml[v2.5.6, v3.0.0].
    - Can only install one of: symfony/yaml[v2.5.7, v3.0.0].
    - Can only install one of: symfony/yaml[v2.5.8, v3.0.0].
    - Can only install one of: symfony/yaml[v2.5.9, v3.0.0].
    - Can only install one of: symfony/yaml[v2.6.0, v3.0.0].
    - Can only install one of: symfony/yaml[v2.6.1, v3.0.0].
    - Can only install one of: symfony/yaml[v2.6.10, v3.0.0].
    - Can only install one of: symfony/yaml[v2.6.11, v3.0.0].
    - Can only install one of: symfony/yaml[v2.6.12, v3.0.0].
    - Can only install one of: symfony/yaml[v2.6.2, v3.0.0].
    - Can only install one of: symfony/yaml[v2.6.3, v3.0.0].
    - Can only install one of: symfony/yaml[v2.6.4, v3.0.0].
    - Can only install one of: symfony/yaml[v2.6.5, v3.0.0].
    - Can only install one of: symfony/yaml[v2.6.6, v3.0.0].
    - Can only install one of: symfony/yaml[v2.6.7, v3.0.0].
    - Can only install one of: symfony/yaml[v2.6.8, v3.0.0].
    - Can only install one of: symfony/yaml[v2.6.9, v3.0.0].
    - Can only install one of: symfony/yaml[v2.7.0, v3.0.0].
    - Can only install one of: symfony/yaml[v2.7.1, v3.0.0].
    - Can only install one of: symfony/yaml[v2.7.2, v3.0.0].
    - Can only install one of: symfony/yaml[v2.7.3, v3.0.0].
    - Can only install one of: symfony/yaml[v2.7.4, v3.0.0].
    - Can only install one of: symfony/yaml[v2.7.5, v3.0.0].
    - Can only install one of: symfony/yaml[v2.7.6, v3.0.0].
    - Can only install one of: symfony/yaml[v2.7.7, v3.0.0].
    - Can only install one of: symfony/yaml[v2.8.0, v3.0.0].
    - Can only install one of: symfony/yaml[2.0.4, v3.0.0].
    - Can only install one of: symfony/yaml[2.0.5, v3.0.0].
    - Can only install one of: symfony/yaml[2.0.6, v3.0.0].
    - Can only install one of: symfony/yaml[2.0.7, v3.0.0].
    - Can only install one of: symfony/yaml[v2.0.10, v3.0.0].
    - Can only install one of: symfony/yaml[v2.0.12, v3.0.0].
    - Can only install one of: symfony/yaml[v2.0.13, v3.0.0].
    - Can only install one of: symfony/yaml[v2.0.14, v3.0.0].
    - Can only install one of: symfony/yaml[v2.0.15, v3.0.0].
    - Can only install one of: symfony/yaml[v2.0.16, v3.0.0].
    - Can only install one of: symfony/yaml[v2.0.17, v3.0.0].
    - Can only install one of: symfony/yaml[v2.0.18, v3.0.0].
    - Can only install one of: symfony/yaml[v2.0.19, v3.0.0].
    - Can only install one of: symfony/yaml[v2.0.20, v3.0.0].
    - Can only install one of: symfony/yaml[v2.0.21, v3.0.0].
    - Can only install one of: symfony/yaml[v2.0.22, v3.0.0].
    - Can only install one of: symfony/yaml[v2.0.23, v3.0.0].
    - Can only install one of: symfony/yaml[v2.0.24, v3.0.0].
    - Can only install one of: symfony/yaml[v2.0.25, v3.0.0].
    - Can only install one of: symfony/yaml[v2.0.9, v3.0.0].
    - Installation request for symfony/yaml == 3.0.0.0 -> satisfiable by symfon
/yaml[v3.0.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by Advil-Robin** [comment]
I got the same issue.

**Comment by frohlfing** [comment]
I got the same issue, too.

My system: 
XAMPP for OS X 5.6.12
Laravel v5.0.33

My composer.json:
"require": {
    "laravel/framework": "5.0.*",
    "barryvdh/laravel-ide-helper": "~2.0",
    "doctrine/dbal": "~2.5",
    "illuminate/html": "~5.0",
    "pda/pheanstalk": "~3.0",
    "nicolaslopezj/searchable": "~1.5",
    "intervention/image": "^2.2",
    "bllim/laravalid": "*"
  },

**Comment by NightZpy** [comment]
Same issue!

**Comment by matthewmnewman** [comment]
After tinkering around with this issue it seems the issue is related to the ua-parser and its dependencies. It seems the package requires Symfony version v2.8.1 rather than v3.0.1 so to get round this issue all you need to do is:

```
composer require symfony/yaml ^2.0 
composer require pragmarx/tracker
```

This will remove ```symfony/yaml(v3.0.1) and replace it with (v2.8.1) ``` which is not an ideal solution but it should fix the dependency issues for now.

**Comment by farrance** [comment]
I had the same issue. Seems my problem was a clash of the yaml dependency with Phinx and PHPUnit. Adding a

`"symfony/yaml": "^3.0",`

To the top of my composer.json solved the issue without the downgrade.
