### ISSUE TITLE
Prevent untracked routes from being logged

### ISSUE THREAD

**Issue by joaodman** [antonioribeiro/tracker#133]
Is there any way to prevent route hits from being logged?
If I add a route to "do_not_track_routes" it is not added to tracker_routes table, but if I visit that route it still adds entries in tracker_log, tracker_sessions and also queries and querie_arguments because I'm tracking them.
The problem is that for every access to the stats page I get a lot of data written to the database, is there any way to prevent this from happening? I tried to change the source code but got lost in the repositories, some help would be welcome.

I'm attaching some prints of the date logged only by accessing the stats page that I would like to get rid of, for example if a session has page_views = 0 it shouldn't be written to the DB.
![stats-panel](https://cloud.githubusercontent.com/assets/6719189/11957244/8ae877fe-a8b8-11e5-9690-b57b0e167fc9.png)

![log_session](https://cloud.githubusercontent.com/assets/6719189/11957243/8ae7694a-a8b8-11e5-8115-54270323ac59.png)

![log_querie_argument](https://cloud.githubusercontent.com/assets/6719189/11957242/8ae6fb72-a8b8-11e5-9400-4a30964291c7.png)

**Comment by joaodman** [comment]
Does anyone have any idea if this can be done, and if it can which files should I git into to accomplish this?
@antonioribeiro may you guide me here, please?

**Comment by antonioribeiro** [comment]
Fixed.
