### ISSUE TITLE
Laravel Sessions 

### ISSUE THREAD

**Issue by matthewmnewman** [antonioribeiro/tracker#137]
I noticed with Laravel 5 + that each request creates a new session and this is causing issues tracking data with the tracker. For example if i wanted to track a users particular referral_id using the log it would create a brand new session for each request meaning that the only way to track that user would be using there IP Address which is not ideal. 

Doing abit of research myself it seems Laravel changed the way sessions work so that if they are used Globally outside the Request Middleware they will not be tracked and a new session would be generated. Not sure if this is the cause but this is not ideal as it means the log becomes huge and tracking reliable data becomes a problem.

Any advice or tips to get around this would be appreciated.

**Comment by farnsworthMars** [comment]
I'm seeing the same issue on installation - overall the package looks awesome and installation went smoothly - but this is a deal breaker for me.  We use database session driver in dev and memcache in prod - not sure if that would make a different - and I've only tried this in dev.

**Comment by deutschehandarbeit** [comment]
Same problem here.

**Comment by antonioribeiro** [comment]
Should be fixed on next version.
