### ISSUE TITLE
Error with Laravel Debugbar package (must implement interface Illuminate\Contracts\Debug\ExceptionHandler)

### ISSUE THREAD

**Issue by bachmay** [antonioribeiro/tracker#138]
I installed the Tracker and Laravel Debugbar (https://github.com/barryvdh/laravel-debugbar). If the Debugbar is enabled and I try to access /stats, I get the following error:

```
ErrorException in Debugbar.php line 29:
Argument 2 passed to Barryvdh\Debugbar\Middleware\Debugbar::__construct() must implement interface Illuminate\Contracts\Debug\ExceptionHandler, instance of PragmaRX\Tracker\Support\Exceptions\Handler given
```
Screenshot:
![screenshot 2016-01-20 23 02 57](https://cloud.githubusercontent.com/assets/6717537/12471270/f7d56f02-bfc9-11e5-997b-61135f118706.png)

The problem is, I am okay with disabling debugbar for that part of my project. However, there is no way to disable Debugbar on only one route or URI.

Any type of help would be greatly appreciated.

Thanks.

**Comment by bachmay** [comment]
This problem actually occurs on all of the pages. I can only enable only one of the 2 packages at a time.

**Comment by KikoPalomares** [comment]
+1

**Comment by Advil-Robin** [comment]
I had the same issue, you just disable the tracker in you development environement.

**Comment by antonioribeiro** [comment]
Current version is working fine with Debugbar:

![image](https://cloud.githubusercontent.com/assets/3182864/17895494/a1de2c20-6923-11e6-8006-1b20afda3126.png)


![image](https://cloud.githubusercontent.com/assets/3182864/17895445/84b824f2-6923-11e6-8019-eec3b32a669c.png)
