### ISSUE TITLE
ErrorException in Datatables.php line 1071: Call to undefined method Bllim\Datatables\Datatables::usingcollection()

### ISSUE THREAD

**Issue by dayatfadila7** [antonioribeiro/tracker#140]
my data in view using yajra/laravel-datatables-oracle work but after install  pragmarx/tracker error
ErrorException in Datatables.php line 1071: Call to undefined method Bllim\Datatables\Datatables::usingcollection()

how to disable blim datatables?
![screenshot](https://cloud.githubusercontent.com/assets/9100806/12542649/76ab4342-c358-11e5-89c7-dc2840f689c7.png)

**Comment by ahmadbadpey** [comment]
Thanks @dayatfadila7 , I had same problem and with your solution that is solved...

**Comment by alinasiri1367** [comment]
Thanks @dayatfadila7

**Comment by meyer59** [comment]
Hi,
Facing the same issue, Can you explained a little bit more the solution ? what do you mean by _reoder Autoloaded Service Providers_ ?  Maybe some code will be helpfull
Thank you

**Comment by meyer59** [comment]
Just find out the solution and probably what did you mean by _reorder_. For those who need a more explained solution:
In you `cong/app.php` in the service provider array, put the providere in this order (Yajra provider on the bottom)
1.    PragmaRX\Tracker\Vendor\Laravel\ServiceProvider::class, //on the top
2.    Yajra\Datatables\DatatablesServiceProvider::class, // on the bottom
3.   Yajra\Datatables\ButtonsServiceProvider::class, // on the bottom
4.    Yajra\Datatables\HtmlServiceProvider::class, // on the bottom
