### ISSUE TITLE
do_not_track_routes does not work

### ISSUE THREAD

**Issue by ahmadbadpey** [antonioribeiro/tracker#142]
I have a route for Admin directory like this : 
```
Route::group(
	array (
		'middleware' => 'IsAdmin',
		'as'         => 'admin::'
	),
	function () {
		Route::get('desktop', [ 'uses' => 'DesktopController@index']);
                //some Other Routes 
        }
)
```

And I do not want to track this routes and sub routes .

For that I change `do_not_track_routes` option like this : 
```
'do_not_track_routes' => [
		'admin.*',
		'tracker.stats.*',
	],
```
But seems this does not work and with every visits Admin or sub Admin directories , add new sessions (or visits) to tracker_sessions table.

**Comment by kevincobain2000** [comment]
Seems like it is not implemented  https://github.com/antonioribeiro/tracker/blob/master/src/Tracker.php#L230

**Comment by Jiedara** [comment]
isTrackableRoute() work better like that : 

    		protected function isTrackableRoute() {
			if (is_null(\Request::path())) {
					return true;
			}
			$routes = $this->config->get('do_not_track_routes');
			foreach ($routes as $route) {
					$match = preg_grep ('/'. $route .'/i', [\Request::path()]);
					if(!empty($match)){
						return false;
					}
			}
			return true;
		}

**Comment by antonioribeiro** [comment]
Fixed.
