### ISSUE TITLE
Duplicate Entry for tracker_agents_name_unique

### ISSUE THREAD

**Issue by joe642** [antonioribeiro/tracker#149]
I received a print screen of this error from a user, unfortunately they did not specify any more details about which page they were on. It looks as though they are using the new Firefox for iOS. I am using this plugin untouched. I can't seem to replicate the error myself.

![image](https://cloud.githubusercontent.com/assets/9432541/12861441/4aa214b8-cc5b-11e5-93e9-2a499387c4b4.png)

**Comment by N02SRT** [comment]
I am also getting this. Any Ideas?

**Comment by antonioribeiro** [comment]
Should be some sort of database problem, because all insertions are done using the `findOrCreate()` method.

If you have more info, please ask to reopen.
