### ISSUE TITLE
Unable to get unique page visits

### ISSUE THREAD

**Issue by sankety** [antonioribeiro/tracker#150]
I have been trying to get **unique page visits** of certain route but no matter what the count always shows 1 

Please let me know if I am doing it wrong or is there any other way
`return Tracker::logByRouteName('home')        
        ->select('tracker_log.session_id')
        ->groupBy('tracker_log.session_id')
        ->distinct()
        ->count('tracker_log.session_id');`

**Comment by divcoders** [comment]
same happening here, returns 1 every time, have anyone got a fix on this yet ?

**Comment by antonioribeiro** [comment]
Should be fixed on next version.
