### ISSUE TITLE
Conflict with using different Datatables package

### ISSUE THREAD

**Issue by scsddeputy** [antonioribeiro/tracker#156]
When using this package along with http://packalyst.com/packages/package/yajra/laravel-datatables-oracle the datatables facade will be registered to this package and over write the yajra datatables package rendering errors on the pages that use it.

**Comment by ahmadbadpey** [comment]
only use _aliases_ and _providers_ of **yajra\Datatables** after **PragmaRX\Tracker** one in  _aliases_ and _providers_ array in _app.php_ file .

**Comment by qrazi** [comment]
Ran into exact same issue. If Bllim\Datatables is only used internally, perhaps use a more specific alias?

**Comment by antonioribeiro** [comment]
Usage of Datatables is namespaced, so I don't see it happening:

    use Bllim\Datatables\Facade\Datatables;
