### ISSUE TITLE
Class 'PragmaRX\Tracker\Vendor\Laravel\ServiceProvider' not found

### ISSUE THREAD

**Issue by basti2305** [antonioribeiro/tracker#162]
I've added _'PragmaRX\Tracker\Vendor\Laravel\ServiceProvider'_ to _providers_ and _'Tracker' => 'PragmaRX\Tracker\Vendor\Laravel\Facade'_ to _aliases_ in my _config/app.php_
When I want to run _php artisan vendor:publish_ it says __Class 'PragmaRX\Tracker\Vendor\Laravel\ServiceProvider' not found__.
Any ideas?

**Comment by gyleodhis** [comment]
I have the same issue; Am running laravel 5.2

**Comment by antonioribeiro** [comment]
Now running fine on Laravel 5.2 and 5.3.

**Comment by jitendra-atx** [comment]
I am using the laravel 5.4 version but have the same issue.

Any Idea?

**Comment by darvishiyan-mahdi** [comment]
i have same issue with laravel 5.5 
and i delete everything related to the package and it still show to error and it doesn't let me use any other composer commands
