### ISSUE TITLE
In tracker_sessions table in database user_id is showing null

### ISSUE THREAD

**Issue by GauravG04** [antonioribeiro/tracker#166]
I am using laravel 5.2, in my database in tracker_sessions tables user_id is is not taking user id

**Comment by Rainesdave** [comment]
I had same issue, so i fork the project and edit the package, Tracker runs in service provider boot method, but Laravel session has not start then and hence the issue above. in my edited version, the tracker runs in the kernel and now everything is perfect. check it out here https://github.com/Rainesdave/tracker.git

**Comment by aftercares** [comment]
@Rainesdave 

When I updated my project of Laravel 5.2 as mentioned from the link mentioned by you, I get the following error:

ErrorException in ClassLoader.php line 412:
include(/Applications/MAMP/htdocs/aftercares/vendor/pragmarx/tracker/src/Vendor/Laravel/Facade.php): failed to open stream: No such file or directory

When I did composer dump autoload the above error got cleared but a new error appeared, which is mentioned below:

ErrorException in AliasLoader.php line 66:
Class 'PragmaRX\Tracker\Vendor\Laravel\Facade' not found

**Comment by tarzanking** [comment]
@Rainesdave I have try use your method which is add `\PragmaRX\Tracker\Vendor\Laravel\TrackerMiddleware::class,` into kernel
but the user_id still getting null

please help ... and thanks

**Comment by Rainesdave** [comment]
@aftercares in your config.php file, your Tracker alias line should look like this

`'Tracker' 	=> PragmaRX\Tracker\Vendor\Laravel\Tracker::class,`

**Comment by Rainesdave** [comment]
@tarzanking if the middleware used is form my git then you will have to use the Service Provider too. I have modified the tracker service provider so it does not boot the tracker. Adding the middleware alone will solve the issue

**Comment by tarzanking** [comment]
thanks @Rainesdave  after i paste `'Tracker' => 'PragmaRX\Tracker\Vendor\Laravel\Tracker',` into my alias and `'PragmaRX\Tracker\Vendor\Laravel\ServiceProvider',` into providers then run `php artisan vendor:publish` in terminal 

It show the output :  
`Copied Directory [/vendor/lrgt/laravel-form-ajax-validation/src/Lrgt/LaravelFormAjaxValidation/views] To [/resources/views/vendor/lrgt]
Copied Directory [/vendor/pragmarx/tracker/src/migrations] To [/database/migrations]`

Last I try to run `{{$visitor = Tracker::currentSession()}}` and it show the error as below : 
`Class 'PragmaRX\Tracker\Vendor\Laravel\Tracker' not found (View: /home/vagrant/Code/food-app/resources/views/admin_page/tracking_page.blade.php)`

**Comment by Rainesdave** [comment]
@tarzanking make sure also require geoip package in your composer json file. Also not that your machine IP which is likely 127.0.0.1 cannot be mapped to any location. Make your application live and check the location again

**Comment by pilishen** [comment]
@tarzanking hey,man, how did u solve it? I installed the latest commit and added the middleware, but no lucky. the user_id still turns null. any help? thanks

**Comment by aftercares** [comment]
@Rainesdave I changed the stuff as you mentioned, but now my every tracker database is empty. Its not recording any stuff, except domain table.

Previously on the antonioribeirol tracker, everything was working expect geoip and user_id. but now nothing is recorded

**Comment by tarzanking** [comment]
@pilishen I have no idea how i solve it ...
Previously i follow the antonioribeirol tracker, everything was working expect geoip and user_id which is @aftercares  mention .

Then I change to Rainesdave tracker with modified the kernel, add middleware and the user_id was appear. But other function cant work.

**Comment by pilishen** [comment]
@Rainesdave any clue?thanks, man.

**Comment by Rainesdave** [comment]
Hi guys, if you use my git, I dont see why everything should not work!! What I have in my git, I have deployed to a live site and all works perfectly.

@tarzanking require and install geoip package, note that your local machine ip which is likely 127.0.0.1 will not display in location table just like this
![screenshot from 2016-04-30 19 42 16](https://cloud.githubusercontent.com/assets/14282239/14937879/f571c0b2-0f0b-11e6-9312-b0be90ccba9a.png)

but on a live site, it works just like this:
![screenshot from 2016-04-30 19 44 02](https://cloud.githubusercontent.com/assets/14282239/14937880/f5ced75c-0f0b-11e6-9e4c-959653132396.png)

@aftercares @pilishen  redownload the git, and use it like that our the box or do 
`composer require rainestech/tracker`

then follow my readme file as regards the middleware and the facade alias

**Comment by Rainesdave** [comment]
@aftercares @tarzanking @pilishen if everything does not work again after adding the middleware to your kernel file, that means you have probably placed it in the wrong place in the kernel file. Using laravel 5.2, your kernel file should look like these:

`<?php

namespace App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
    ];

    /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \PragmaRX\Tracker\Vendor\Laravel\TrackerMiddleware::class,
        ],

        'api' => [
            'throttle:60,1',
        ],
    ];

    /**
     * The application's route middleware.
     *
     * These middleware may be assigned to groups or used individually.
     *
     * @var array
     */
    protected $routeMiddleware = [
        'auth' => \App\Http\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
    ];
}
`

Note that the middleware is added to the web group after laravel session. The tracker middleware has to be added after laravel session and in the same place with laravel session should your kernel file be different

**Comment by aftercares** [comment]
@Rainesdave Hey, now everything is working perfect. I missed putting "\PragmaRX\Tracker\Vendor\Laravel\TrackerMiddleware::class,"  into my kernel.php file.

Thanks for your time and effort. Thank you

**Comment by pilishen** [comment]
@Rainesdave yeah! It's working. my mistake is that i put the middleware in $middleware, instead of $middlewareGroups. maybe you can specify it in readme file. 
thanks a lot, you are trully helpful.

**Comment by SephVelut** [comment]
Installed you fork via composer but I'm getting a `Class PragmaRX\Tracker\Vendor\Laravel\TrackerMiddleware does not exist`. This happend when I try to set the middleware in the kernel.php.

**Comment by diegorodriguezvidal** [comment]
I am looking for some help, I tried @antonioribeiro version and then I tried your version as well @Rainesdave . In both versions routes tracking is not working, I've got everything set to true in the tracker.php file and also other tables are working fine. Any idea about why is this happening?

**Comment by cbenjamin** [comment]
Same problem as you @diegorodriguezvidal... I have middleware in place. Everything logs well except user_id is always NULL.I am using Sentinel as my auth.

**Comment by antonioribeiro** [comment]
Tested on Laravel 5.2 and 5.3, version 2.0.5 works fine for me.

**Comment by MehdiM62** [comment]
I am using v3.2.2 on Laravel 5.4. The user_Id is always null. I have multi authentication. Only admin have access to Stats panel. I'm trying to have the tracking for normal user(App\Admin). I'm testing on local(vagrant) 
![image](https://user-images.githubusercontent.com/19629619/31497632-4041fbb6-af92-11e7-9655-f8120ff07770.png)

tracker.php:
```
    'use_middleware' => true,
    'log_users' => true,
    'user_model' => 'App\Admin',
    'authentication_ioc_binding' => ['auth','App\Admin'],
    'authenticated_check_method' => 'check',
    'authenticated_user_method' => 'user', 
    'authenticated_user_id_column' => 'id',
    'authenticated_user_username_column' => 'email',
    'stats_routes_middleware' => 'web',
```

**Comment by MehdiM62** [comment]
I resolve this issue by modifying ```'user_model' =>'App\User```. My mistake was setting my model to admin user.
