### ISSUE TITLE
I find a little problem.

### ISSUE THREAD

**Issue by 1007380462** [antonioribeiro/tracker#171]
first time when i access to http://192.168.157.130:8080/stats?page=visits .
laravel framwork display below errors:
 InvalidArgumentException in Builder.php line 465:
Illegal operator and value combination.
I found that result is invoke Base.php file's scopePeriod function .when $minutes->getStart() and $minutes->getEnd() is null ,will report error. 
 I modify the  scopePeriod function to the form below: 

public function scopePeriod($query, $minutes, $alias = '')
	{
		$alias = $alias ? "$alias." : '';
		return $query
				->where($alias.'updated_at', '>=', $minutes->getStart()?$minutes->getStart():1)
				->where($alias.'updated_at', '<=', $minutes->getEnd()?$minutes->getEnd():1);
	}
when i visit the http://192.168.157.130:8080/stats?page=visits  again  not  an error. 
I don't know if it is mistakes.I just share  my experience of my solve problem with people  .

**Comment by antonioribeiro** [comment]
Add it to the code, nice, thank you!
