### ISSUE TITLE
device->platform showing non object property.

### ISSUE THREAD

**Issue by javedLive** [antonioribeiro/tracker#172]
I want to access my client device name using antonioribeiro/tracker.
But while i dd() the out put it's showing 'Non Object Property'

 ```
public function postUser(Request $request)
    {
    	$user=new User();
    	$user->name= $request->Input(['name']);
    	$user->email=$request->Input(['email']);
    	$user = Tracker::currentSession();
    	dd($user->device->platform) ;
    	//dd( $user->device->is_mobile);
 
    	$user->save();
    	return redirect('userPage');
    }
```

**Comment by antonioribeiro** [comment]
As long as you are logging devices, it works.

![image](https://cloud.githubusercontent.com/assets/3182864/17896449/12da0bda-6927-11e6-8bbf-afd0ef44f341.png)

![image](https://cloud.githubusercontent.com/assets/3182864/17896460/1f4f378c-6927-11e6-8ada-360ef61926e4.png)
