### ISSUE TITLE
$visitor = Tracker::currentSession(); Doesn't work.

### ISSUE THREAD

**Issue by SpaceNL** [antonioribeiro/tracker#173]
I installed everything, have a working database for the tracker but when I type:

`$visitor = Tracker::currentSession();`

I get an error: "Non-static method PragmaRX\Tracker\Tracker::currentSession() should not be called statically"

Does anybody know a solution?

**Comment by SpaceNL** [comment]
I figured it out:

`use PragmaRX\Tracker\Vendor\Laravel\Facade as tracker;`

**Comment by emmerink** [comment]
`use Tracker;`

should also do when the Facade is registered in `config/app.php` (it may even be discovered but didn't check that)
