### ISSUE TITLE
running php artisan vendor:publish brings errors

### ISSUE THREAD

**Issue by gyleodhis** [antonioribeiro/tracker#176]
I've added 'PragmaRX\Tracker\Vendor\Laravel\ServiceProvider' to providers and 'Tracker' => 'PragmaRX\Tracker\Vendor\Laravel\Facade' to aliases in my config/app.php
When I want to run php artisan vendor:publish it says Class 'PragmaRX\Tracker\Vendor\Laravel\ServiceProvider' not found.
Any ideas?

Am running laravel 5.2

**Comment by antonioribeiro** [comment]
No errors running with the current version.

![image](https://cloud.githubusercontent.com/assets/3182864/17878285/284c9e9a-68c0-11e6-8f5d-768e54238634.png)
