### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by thusfar7** [antonioribeiro/tracker#177]
What should I do about this error?

https://www.dropbox.com/s/qbbtu4jahd0n6kv/Screenshot%202016-07-02%2009.41.31.png?dl=0

**Comment by thusfar7** [comment]
Anyone?

**Comment by brobyns** [comment]
It looks to me as though you need to remove ramsey/uuid 3.4.1 first, since tracker makes use of the older 2.8 version of ramsey/uuid.

**Comment by thusfar7** [comment]
Would an older version brake Laravel?

**Comment by thusfar7** [comment]
@antonioribeiro You should fix this

**Comment by antonioribeiro** [comment]
It's fixed. Ramsey was bumped.
