### ISSUE TITLE
Unique visitors in antonioribeiro/tracker laravel package

### ISSUE THREAD

**Issue by ahmadbadpey** [antonioribeiro/tracker#180]
I am using antonioribeiro/tracker laravel package to store user tracker information.

In this package there are many useful method to get information. for example there is a sessions() method to get all visits on past day:

`$todayVisits   = Tracker::sessions(60 * 24)->count();`

But I do not know how can I get Unique visitors of past day.

Of course there is a users() method that return count of registered users that visit pages:

`$todayVisitors = Tracker::users(60 * 24)->count();`

But I want to count visit of guest users that are not really registered.

How Can I do that?

**Comment by DamianImrich** [comment]
I have same problem with getting unique visitors. Tracker cookie expire after reload and tracker generarate new cookie with session uuid. Because session uuid is regenerating every load, I have same pageViews and sessions count.

**Comment by ahmadbadpey** [comment]
you can use this code to get online visitors in last 30 seconds:
```
$onlineVisitors =
DB::table('tracker_sessions')->where('created_at', '>=', Carbon::now()->subSeconds(30))->count(); 
```

**Comment by DamianImrich** [comment]
I don't need online visitors. I need unique sessions(visitors) like you in first post...

**Comment by antonioribeiro** [comment]
There was a bug related to sessions. Should be fixed on next version.

**Comment by antonioribeiro** [comment]
You also have access to this now:

    $users = Tracker::onlineUsers();
