### ISSUE TITLE
404 for the sb-admin 

### ISSUE THREAD

**Issue by rorystandley** [antonioribeiro/tracker#181]
I've tried running through the readme to get the admin setup but getting a 404 -

https://github.com/IronSummitMedia/startbootstrap-sb-admin-2/archive/v1.0.7.zip

Thanks
Rory

**Comment by alireza-ansaripour** [comment]
https://github.com/BlackrockDigital/startbootstrap-sb-admin-2/archive/master.zip
try this

**Comment by antonioribeiro** [comment]
Readme fixed.
