### ISSUE TITLE
v2.0.9 | General error: 1215 Cannot add foreign key constraint

### ISSUE THREAD

**Issue by tokn** [antonioribeiro/tracker#189]
I've had a look through the closed issues and i've spotted that a similar issue arose but that was with a previous update and after reporting it got fixed. Is this instance a similar problem that needs a source fix or does this indicate a separate issue, perhaps with my configuration?

**Comment by tokn** [comment]
[Illuminate\Database\QueryException]                                                                                                                                                                             
  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `tracker_sessions` add constraint `tracke  
  r_sessions_language_id_foreign` foreign key (`language_id`) references `tracker_languages` (`id`) on delete cascade on update cascade))

**Comment by antonioribeiro** [comment]
Have you migrate:rollback the last batch?
It cannot add that foreign key because a column was created with the wrong type.

**Comment by antonioribeiro** [comment]
Worked for them: https://github.com/antonioribeiro/tracker/issues/186#issuecomment-241977916

**Comment by tokn** [comment]
php artisan migrate:rollback 
Rolled back: 2015_11_23_311098_add_language_id_column_to_sessions
Rolled back: 2015_11_23_311097_create_tracker_languages_table

                                                                                                                                                                                                                   
  [Illuminate\Database\QueryException]                                                                                                                                                                             
  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `tracker_sessions` add constraint `tracke  
  r_sessions_language_id_foreign` foreign key (`language_id`) references `tracker_languages` (`id`) on delete cascade on update cascade))                                                                          
                                                                                                                                                                                                                   

                                                                          
  [PDOException]                                                          
  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint  


**Weirdly doesn't seem to have helped**, thanks for the support Antonio. Any other ideas?

**Comment by antonioribeiro** [comment]
Weird. But I think I may have got it: you have to upgrade your migrations.

1) Rollback the migration again.

2) Delete the following files from your database\migrations:

    2015_11_23_311097_create_tracker_languages_table.php    
    2015_11_23_311098_add_language_id_column_to_sessions.php    
    2015_11_23_311099_add_tracker_language_foreign_key_to_sessions.php  
    2015_11_23_311100_add_nullable_to_tracker_error.php

2) Run `php artisan tracker:tables` to upgrade them

3) Migrate.

**Comment by antonioribeiro** [comment]
How is it?

**Comment by tokn** [comment]
Migrations have now run correctly following the latest advice. Thanks very much for your support @antonioribeiro.
