### ISSUE TITLE
Tracker creates a new session in database on each request

### ISSUE THREAD

**Issue by simplewebteam** [antonioribeiro/tracker#193]
on each request or page refresh, a new session is currently being created in tracker_sessions.

**Comment by finks86** [comment]
+1

**Comment by ppisecky** [comment]
Is there any workaround or solution to this? It seems like this project has been abandoned.

**Comment by vishalNagpure** [comment]
I am facing same issue 
on  each refresh new session created

**Comment by mohabhassan** [comment]
Guys I found the only solution:
`composer require pragmarx/tracker 3.0.0`

**Comment by antonioribeiro** [comment]
Was merged. Thank you

**Comment by tokkerbaz** [comment]
I am using v3.3, but same problem
