### ISSUE TITLE
tracker.users is not found

### ISSUE THREAD

**Issue by carkii** [antonioribeiro/tracker#194]
Hi, 
I have tried this tracker and it works perfectly when i keep all tracker tables in same app "main" database.

In order to keep my database & files organized, I have created new database called "tracker" where it can hold all trackers' tables. Suddenly, I received error says "tracker.users is not available". I believe that this errors appeared because "users" table is available in my "main" database and not available in "tracker" database.

Is there any solution for this issue, or should I change core codes of the project? 

Thank you in advance :)

**Comment by brazorf** [comment]
I'm having the same problem, my users table is in another database. How did you fix?

**Comment by carkii** [comment]
@brazorf in config/tracker.php change:
from:
 'user_model' => 'PragmaRX\Tracker\Vendor\Laravel\Models\User' 
to:
  'user_model' => 'App\User'

, so it will use User model from the App itself

**Comment by brazorf** [comment]
How's that supposed to fix? Issue it's related to a database connection, not a database Model.

However, that issue disappeared for me out of nothing (probably a flush_all on my memcached instance), i believe it might have to do with cached values since i was switching between 2 database while testing the package.

**Comment by carkii** [comment]
'App\User' Keeps using the Original connection of the App "mysql".

while 'PragmaRX\Tracker\Vendor\Laravel\Models\User'  uses the connection of the "tracker"

So, 'App\User' will keep reading Original connection of your App. 

Good luck.

**Comment by brazorf** [comment]
I'm not using App\User but another custom user Model. However this sounds new to me, can we set which connection to use at Model level? (Sorry for the OT).

**Comment by amylashley** [comment]
@brazorf I was only able to get this to work by adding the following variable to my User model file ('mysql' is my default connection). 

`protected $connection = 'mysql';`

You will also need to update the 'user_model' path in your tracker.php file to point to your custom model location (mine is App\Models\User)
