### ISSUE TITLE
Error on Migration

### ISSUE THREAD

**Issue by youngbobby** [antonioribeiro/tracker#195]
Hi,

I followed all the instructions and I'm currently stuck at migrating my tables. I am on Laravel 5.3

This is the error I get on migration.

```
[Illuminate\Database\QueryException]                                                                                                                                                          
  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'updated_at' (SQL: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'upda  
  ted_at' (SQL: create table `tracker_paths` (`id` bigint unsigned not null auto_increment primary key, `path` varchar(255) not null, `created_at` timestamp not null, `updated_at` timestamp   
  not null) default character set utf8 collate utf8_unicode_ci))   
```

**Comment by Kyslik** [comment]
What kind of SQL server do you run? (MySql 5.7.14)

Do you use `strict => true` in /config/database,php?


For more info read all this https://github.com/laravel/framework/issues/3602#issuecomment-107154710

**Comment by youngbobby** [comment]
@Kyslik I run MySql 5.7.13 and Yes, `strict` is set to `true` by default on Laravel. :(

**Comment by Kyslik** [comment]
I just installed this on fresh 5.3 and get same error(s) as you do, from link above if you remove `NO_ZERO_DATE` from mode it should work, but **that is not a real solution**, package needs some updates!

Laravel way how `$table->timestamps()` work.
```
public function timestamps()
{
    $this->timestamp('created_at')->nullable();
    $this->timestamp('updated_at')->nullable();
}
```
Package way

```
$table->timestamp('created_at')->index();
$table->timestamp('updated_at')->index();
```

---
#### Possible fix

```
$table->timestamp('created_at')->nullable()->index();
$table->timestamp('updated_at')->nullable()->index();
```
---

Please make an select to check mode

`SELECT @@GLOBAL.sql_mode;`

mine outputs:
```
ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
```

**Comment by ctf0** [comment]
for the issue with strict mode true , check 
https://laravel.com/docs/5.3/upgrade#upgrade-5.2.0 @ MySQL Dates , kinda dump that something like that wasnt proberly documented

**Comment by napestershine** [comment]
It's already mentioned in readme

```
 'tracker' => [
    	'driver'   => '...',
    	'host'     => '...',
    	'database' => ...,
        'strict' => false,    // to avoid problems on some MySQL installs
    	...
    ],
```
