### ISSUE TITLE
Lang Problem

### ISSUE THREAD

**Issue by d1c1pl3** [antonioribeiro/tracker#215]
I have a problem with the langs, in the stats all texts are shown like this:
tracker::tracker.visits

does anybody know why?

**Comment by pxpm** [comment]
Probably you are missing publishing package lang file .. check your lang folder for a file called Tracker.php

**Comment by d1c1pl3** [comment]
No as I see it right this is not necessary.

I just tried it with a new clean Laravel 5.4 installation and there it works. I have no clue why it doesn't work in my main project, but it seems to be a project-specific problem.
