### ISSUE TITLE
Not fine in laravel 5.3

### ISSUE THREAD

**Issue by alinasiri1367** [antonioribeiro/tracker#227]
Hi
This package does not work in Laravel 5.3.
When I run `php artisan migrate`:

> [Illuminate\Database\QueryException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxxxxxxxxx.tracker_sessions' doesn't exist (SQL: SQLSTATE[42S02]: Base table or view
  not found: 1146 Table 'xxxxxxxxxx.tracker_sessions' doesn't exist (SQL: alter table `tracker_sessions` add `language_id` bigint unsigned null))
  [PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxxxxxxxxx.tracker_sessions' doesn't exist

**Comment by joshharington** [comment]
In the migrations, change

````
$table->timestamp('created_at')->index();
$table->timestamp('updated_at')->index();
````

with 

````
$table->timestamps();
````

**Comment by alinasiri1367** [comment]
Again this error :

> QueryException in Connection.php line 769:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'language_id' in 'field list' (SQL: insert into `tracker_sessions` (`user_id`, `device_id`, `client_ip`, `geoip_id`, `agent_id`, `referer_id`, `cookie_id`, `language_id`, `is_robot`, `uuid`, `updated_at`, `created_at`) values (, , ::1, , , , , , 0, 835857fe-e1b8-4ad0-9426-f0973a153cab, 2016-12-18 10:14:28, 2016-12-18 10:14:28))
