### ISSUE TITLE
Different ID in user model

### ISSUE THREAD

**Issue by joshharington** [antonioribeiro/tracker#229]
I am currently getting the following error in Laravel 5.3:

````
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.id' in 'where clause' (SQL: select * from `users` where `users`.`id` in (0))
````

The ID in my user model is `user_id` and not `id`.

I have tried setting the `authenticated_user_id_column` in tracker.php to `user_id` but it didn't fix it. Any way to fix this?

Thanks,
Josh

**Comment by antonioribeiro** [comment]
Could you please give use the full call stack?

**Comment by napestershine** [comment]
#301
