### ISSUE TITLE
Integrity constraint violation: 1062

### ISSUE THREAD

**Issue by abada** [antonioribeiro/tracker#233]
Integrity constraint violation: 1062 Duplicate entry 'Mozilla/5.0 (Linux; Android 6.0.1; SM-N920C Build/MMB29K; wv) Ap' for key 'tracker_agents_name_unique'

**Comment by pxpm** [comment]
#211 have a solution for this problem. You should check related issues before posting new ones with same old questions.

**Comment by antonioribeiro** [comment]
Fixed.
