### ISSUE TITLE
timeline.css file removed and merged into sb-admin-2.css in v3.3.7+1 version

### ISSUE THREAD

**Issue by dastiw1** [antonioribeiro/tracker#236]
timeline.css file removed and merged into sb-admin-2.css in v3.3.7+1 version
[https://github.com/BlackrockDigital/startbootstrap-sb-admin-2/releases/tag/v3.3.7%2B1](https://github.com/BlackrockDigital/startbootstrap-sb-admin-2/releases/tag/v3.3.7%2B1)

**Comment by antonioribeiro** [comment]
Upgraded SBAdmin 2 to v3.3.7+1
