### ISSUE TITLE
Bulk bugs

### ISSUE THREAD

**Issue by dmitryuk** [antonioribeiro/tracker#245]
1. Where I going to Errors tab where is exception:
`Error: SQLSTATE[42702]: Ambiguous column: 7 ERROR: column reference "id" is ambiguous LINE 1: select "id", "error_id", "session_id", "path_id", "updated_a... ^ (SQL: select "id", "error_id", "session_id", "path_id", "updated_at" from "tracker_log" left join "tracker_errors" on "tracker_log"."error_id" = "tracker_errors"."id" where "tracker_log"."updated_at" >= 2017-02-07 07:13:31 and "tracker_log"."updated_at" <= 2017-02-08 07:13:31 and "error_id" is not null order by "created_at" desc, "tracker_errors"."code" asc limit 10 offset 0)`

2. Also please change length of "source" column in tracker_referers  from varchar(255) to type TEXT, because referer from facebook adv throws error
`String data, right truncated: 7 ERROR: value too long for type character varying(255) (SQL: insert into "tracker_referers" ("url", "host", "domain_id", "medium", "source", "search_terms_hash", "updated_at", "created_at") values (https://l.facebook.com/l.phpl.facebook.comu=https%3A%2F%2Fxxxxxxxx%2F%3Futm_source%3Dtarget_fb%26utm_campaign%3Dtraffic%26utm_medium%3Dcpc%26utm_term%3DKZ-18plus-RUlang&h=ATOffpYwCBg0bKb-5Iinn_XLztIj0cGe3DzRuqUt8vZVK5W74RQCIkN3Gcfff6XZ4nVJvpx47img05YVJ62aiprh-KdK4JNppZ0Cxj-d4Kg, 17, social, Facebook, xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, 2017-02-08 08:50:29, 2017-02-08 08:50:29, ?) returning "id")`
3. lang/en/tracker.php
`'no_days'                  => ':count Day|Days',`
should be changed to 
`'no_days'                  => ':count Day|:count Days',`
no_years too

4. tracker_queries, change column query to text
 Error: SQLSTATE[22001]: String data, right truncated: 7 ERROR: value too long for type character varying(255) (SQL: insert into "tracker_queries" ("query", "updated_at", "created_at") values (urlwww_google_essa=t|rct=j|q=|esrc=s|source=web|cd=3|ved=0CDQQFjAF|url=http://robo.cash/2017-02-13 02:34:27utm_source=google-adwords&utm_medium=search&utm_campaign=Test-invest-Latv&utm_term=Procent&utm_content=%D0%BF%D0%BE%D0%BB%D0%BE%D0%B6%D0%B8%D1%82%D1%8C%20%D0%B4%D0%B5%D0%BD%D1%8C%D0%B3%D0%B8%20%D0%BF%D0%BE%D0%B4%20%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D0%BD%D1%82%D1%8B|ei=ZLegWOSsLanVTuGfAQ|usg=AFQjCNF_bvZQAbqCPjn-fw5j1BlY0u7I2w, 2017-02-13 02:34:27, ?) returning "id")
5. tracker_referers change url to text
Error: SQLSTATE[22001]: String data, right truncated: 7 ERROR: value too long for type character varying(255) (SQL: insert into "tracker_referers" ("url", "host", "domain_id", "medium", "source", "search_terms_hash", "updated_at", "created_at") values (http://www.google.lv/urlwww.google.lvsa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0CEEQFjAB&url=http%3A%2F%2Frobo.cash%2F%3Futm_source%3Dgoogle-adwords%26utm_medium%3Dsearch%26utm_campaign%3DTest-invest-Latv%26utm_term%3DKuda%26utm_content%3D%25D0%25BA%25D1%2583%25D0%25B4%25D0%25B0%2520%25D0%25B2%25D0%25BB%25D0%25BE%25D0%25B6%25D0%25B8%25D1%2582%25D1%258C%2520%25D0%25B4%25D0%25B5%25D0%25BD%25D1%258C%25D0%25B3%25D0%25B8%2520%25D0%25BF%25D0%25BE%25D0%25B4%2520%25D0%25BF%25D1%2580%25D0%25BE%25D1%2586%25D0%25B5%25D0%25BD%25D1%2582%25D1%258B&ei=I7egWJqdCau3lgbEEA&usg=AFQjCNFu79iRg7k2IMrpwyPviGHamjhtow, 13, search, Google, da39a3ee5e6b4b0d3255bfef95601890afd80709, 2017-02-12 19:27:32, 2017-02-12 19:27:32, ?) returning "id")
6. tracker_agents name to text
Error: SQLSTATE[22001]: String data, right truncated: 7 ERROR: value too long for type character varying(255) (SQL: insert into "tracker_agents" ("name", "browser", "browser_version", "updated_at", "created_at") values (Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_4 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13G35 [FBAN/FBIOS;FBAV/66.0.0.42.70;FBBV/40764466;FBRV/0;FBDV/iPhone7,2;FBMD/iPhone;FBSN/iPhone OS;FBSV/9.3.4;FBSS/2;FBCR/Carrier;FBID/phone;FBLC/ru_RU;FBOP/5], Facebook, 66.0.0, 2017-02-11 00:39:37, 2017-02-11 00:39:37) returning "id")

7. ERROR: duplicate key value violates unique constraint "tracker_agents_name_unique"
DETAIL: Key (name)=(Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0) already exists.

**Comment by xakzona** [comment]
Also please change length of "source" column in tracker_referers  from varchar(255) to type TEXT, because referer from facebook adv throws error

**Comment by dmitryuk** [comment]
No updates
