### ISSUE TITLE
Add referer parsing

### ISSUE THREAD

**Issue by alexanderdean** [antonioribeiro/tracker#25]
https://github.com/snowplow/referer-parser/tree/master/php

**Comment by antonioribeiro** [comment]
It could be nice to have some more info about the referer, but I can only add "stable" tagged packages, unfortunatelly last version tag is 300 commits old.

**Comment by NoelDavies** [comment]
I could fork it and continue it's progress?

**Comment by antonioribeiro** [comment]
@NoelDavies: not sure what you mean, fork Tracker and add the referer-parser to it? Sure :)

But I will only be able to merge and tag a version when Snowplow tag a stable version of referer-parser themselves.

**Comment by NoelDavies** [comment]
Sorry I meant the refer-parser, or we could just bug them for a stable version?

**Comment by antonioribeiro** [comment]
I did that with 

UA-Parser: https://github.com/antonioribeiro/ua-parser

and

Datatables: https://github.com/antonioribeiro/laravel4-datatables-package

But both packages were already (probably) very stable, with many versions tagged. Last general version of snowplow/referer-parser is 326 commits old. But now looking they have a tag java-scala-0.2.3, which is up to date with master, but why tag it Java/Scala? PHP development stalled?

IMO we have two options: bug them (already bugging https://github.com/snowplow/referer-parser/issues/95) or find a replacement.

What do you think?

**Comment by alexanderdean** [comment]
I've created a tag now, so it should filter through to Packagist in a bit...

**Comment by antonioribeiro** [comment]
@NoelDavies: We have a tag for PHP: https://github.com/snowplow/referer-parser/tree/php-0.1.0 :)

**Comment by antonioribeiro** [comment]
Thanks a lot, @alexanderdean, will try to work somethig out of it asap.

**Comment by NoelDavies** [comment]
@antonioribeiro that's awesome!

**Comment by antonioribeiro** [comment]
@NoelDavies We will have to wait a bit more: https://github.com/snowplow/referer-parser/issues/95#issuecomment-79245295

**Comment by antonioribeiro** [comment]
Just pushed referer parsing to master, enjoy!
