### ISSUE TITLE
Syntax error or access violation: 1071 Specified key was too long

### ISSUE THREAD

**Issue by angelorc** [antonioribeiro/tracker#257]
C:\Users\Angelo\Documents\Progetti\adminlte>php artisan migrate --database=tracker
Migration table created successfully.

  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (S
  QL: alter table `tracker_languages` add unique `tracker_languages_preference_language_range_unique`(`preference`, `
  language-range`)) (SQL: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key
   length is 1000 bytes (SQL: alter table `tracker_languages` add unique `tracker_languages_preference_language_range
  _unique`(`preference`, `language-range`)))

  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (S
  QL: alter table `tracker_languages` add unique `tracker_languages_preference_language_range_unique`(`preference`, `
  language-range`))

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

**Comment by aamirchaudhary** [comment]
Laravel 5.4 made a change to the default database character set, and it’s now utf8mb4 which includes support for storing emojis. This only affects new applications and as long as you are running MySQL v5.7.7 and higher you do not need to do anything.

For those running MariaDB or older versions of MySQL you may hit this error when trying to run migrations:

[Illuminate\Database\QueryException]
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table users add unique users_email_unique(email))

[PDOException]
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
As outlined in the Migrations guide to fix this all you have to do is edit your AppServiceProvider.php file and inside the boot method set a default string length:

use Illuminate\Support\Facades\Schema;

public function boot()
{
    Schema::defaultStringLength(191);
}
After that everything should work as normal.

source =https://laravel-news.com/laravel-5-4-key-too-long-error

**Comment by WBDC** [comment]
> After that everything should work as normal.

On L6 unfortunately not. 
I still get the same error even though I've added the Schema::defaultStringLength(191); to AppServiceProvider

The exact error I'm getting is 
` Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `tracker_languages` add unique `tracker_languages_preference_language_range_unique`(`preference`, `language-range`)) (SQL: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `tracker_languages` add unique `tracker_languages_preference_language_range_unique`(`preference`, `language-range`)))`
