### ISSUE TITLE
Database [tracker] not configured.

### ISSUE THREAD

**Issue by Adnamr** [antonioribeiro/tracker#260]
what the problem here ?!

**Comment by kiarash3tar** [comment]
what's your config? it would be better if you show some code!!

**Comment by Adnamr** [comment]
<?php

return [

  
    'default' => env('DB_CONNECTION', 'mysql'),

  

    'connections' => [

        'sqlite' => [
            'driver' => 'sqlite',
            'database' => env('DB_DATABASE', database_path('database.sqlite')),
            'prefix' => '',
        ],

        'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],

        'pgsql' => [
            'driver' => 'pgsql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '5432'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'schema' => 'public',
            'sslmode' => 'prefer',
        ],

    ],

    /*
    |--------------------------------------------------------------------------
    | Migration Repository Table
    |--------------------------------------------------------------------------
    |
    | This table keeps track of all the migrations that have already run for
    | your application. Using this information, we can determine which of
    | the migrations on disk haven't actually been run in the database.
    |
    */

    'migrations' => 'migrations',

    /*
    |--------------------------------------------------------------------------
    | Redis Databases
    |--------------------------------------------------------------------------
    |
    | Redis is an open source, fast, and advanced key-value store that also
    | provides a richer set of commands than a typical key-value systems
    | such as APC or Memcached. Laravel makes it easy to dig right in.
    |
    */

    'redis' => [

        'client' => 'predis',

        'default' => [
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => 0,
        ],

    ],


];

**Comment by Adnamr** [comment]
![traker1](https://cloud.githubusercontent.com/assets/24726105/24332902/7e47aada-1246-11e7-8c2b-6d400bbd014f.JPG)
![traker2](https://cloud.githubusercontent.com/assets/24726105/24332903/81a359a4-1246-11e7-8355-87c681c970e8.JPG)
![Uploading traker3.JPG…]()

**Comment by Adnamr** [comment]
i think this package doesn't  work any more

**Comment by kiarash3tar** [comment]
well, I did use this  just two days ago and that was great, I don't see your tracker config here
in your `config/database.php` you have to set
```
        'tracker' => [
            'driver'   => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
        ],

```
and there would be a `tracker.php` inside of `config` folder that you can configure your tracker system.
please do these and let me know is there any issue again.

remember to change `'enabled' => false,` to `'enabled' => true,` in the tracker.php if you want your tracker work...

**Comment by Adnamr** [comment]
Thank u it's working but i have anthore problem in migration 
![traker1](https://cloud.githubusercontent.com/assets/24726105/24373208/8adfe46e-1328-11e7-83ee-3c1c4f905bba.JPG)
do u have any idea about that and thank u and i am sorry for my bad english

**Comment by kiarash3tar** [comment]
It's OK because my english is as yours :-)
You have to set this in `providers/AppServiceProvider.php` and inside boot method:

`Schema::defaultStringLength(191);`

And remember to use the `Schema` facade:
`use Illuminate\Support\Facades\Schema;`

This will solve your problem probably.
And for another possible isuues I want to mention that if you use something like `mysql workbench` to take a look at tracker database structure, you'll see that tracker will use relational database structure means some table's column is related to another table and you have to be careful about deleting or manipulating the tables...
I suggest you to use tracker when your development was completely finished...-(it's my opinion)-

**Comment by patricmutwiri** [comment]
The issue is with where you're placing your configs. Put them inside `connections` as below. Ignore the mysqli bit. Was messing with it a little. 
![shot_034](https://user-images.githubusercontent.com/7590159/27393669-9975d74a-56b2-11e7-97be-562ceaa2ba4e.png)

**Comment by antonioribeiro** [comment]
It's really important to read carefully all the docs, and you should not have problems to install and use it:

![image](https://user-images.githubusercontent.com/3182864/27393838-b6c1fd42-5680-11e7-8e9c-9edca576e5f5.png)

**Comment by lipasite** [comment]
I have the same error, I posted the code for the tracker, and indicated it as the default connection.
`'connections' => [

        'sqlite' => [
            'driver' => 'sqlite',
            'database' => env('DB_DATABASE', database_path('database.sqlite')),
            'prefix' => '',
        ],

        'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],

        'tracker' => [
            'driver'   => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'strict' => false,
        ],`

Then I change default connection to 'tracker':
`'default' => env('DB_CONNECTION', 'tracker'),`

After that I run the command
`php artisan migrate`
and see the error:
**Database [tracker] not configured.**

**Comment by enasellithy** [comment]
try that 
'tracker' => [
            'driver' => env('DB_CONNECTION','mysqli'),
            'host' => env('DB_HOST','127.0.0.1'),
            'database' => env('DB_TRACKER','med'),
            'username' => env('DB_USERNAME','tracker'),
            'password' => env('DB_PASSWORD','tracker'),
        ],

**Comment by erikhu** [comment]
> I have the same error, I posted the code for the tracker, and indicated it as the default connection.
> `'connections' => [
> 
> ```
>     'sqlite' => [
>         'driver' => 'sqlite',
>         'database' => env('DB_DATABASE', database_path('database.sqlite')),
>         'prefix' => '',
>     ],
> 
>     'mysql' => [
>         'driver' => 'mysql',
>         'host' => env('DB_HOST', '127.0.0.1'),
>         'port' => env('DB_PORT', '3306'),
>         'database' => env('DB_DATABASE', 'forge'),
>         'username' => env('DB_USERNAME', 'forge'),
>         'password' => env('DB_PASSWORD', ''),
>         'unix_socket' => env('DB_SOCKET', ''),
>         'charset' => 'utf8mb4',
>         'collation' => 'utf8mb4_unicode_ci',
>         'prefix' => '',
>         'strict' => true,
>         'engine' => null,
>     ],
> 
>     'tracker' => [
>         'driver'   => 'mysql',
>         'host' => env('DB_HOST', '127.0.0.1'),
>         'port' => env('DB_PORT', '3306'),
>         'database' => env('DB_DATABASE', 'forge'),
>         'username' => env('DB_USERNAME', 'forge'),
>         'password' => env('DB_PASSWORD', ''),
>         'charset' => 'utf8mb4',
>         'collation' => 'utf8mb4_unicode_ci',
>         'strict' => false,
>     ],`
> ```
> 
> Then I change default connection to 'tracker':
> `'default' => env('DB_CONNECTION', 'tracker'),`
> 
> After that I run the command
> `php artisan migrate`
> and see the error:
> **Database [tracker] not configured.**
> 
> Problem solved after running
> **php artisan config:cache**

that command line is used only in production to boost but i have the same problem after i did the migration and i dont understand why and when active use_middleware => true
