### ISSUE TITLE
Project deprecation

### ISSUE THREAD

**Issue by l-lawliett** [antonioribeiro/tracker#292]
How long will you continue this awesome project just need to know how long to know how much I should invest its great. I am new but I got it up an running plus I want to study it so maybe I could do my own support okay let me know asap.

**Comment by antonioribeiro** [comment]
I'm not planning to stop supporting it, so it should live as long as I do 😂

**Comment by l-lawliett** [comment]
Thanks man am telling you it is a god gift keep it up. You should av a donate button the people love this the more they will donate. Pardon my anime Picture okay lol
