### ISSUE TITLE
Unknown column 'users.id' in 'where clause'

### ISSUE THREAD

**Issue by sebastianstoll97** [antonioribeiro/tracker#301]
My primary key for users table is user_id, not id.

I get the error: 

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.id' in 'where clause' (SQL: select * from `users` where `users`.`id` in ())
--
 
Where In config should this be set?

**Comment by napestershine** [comment]
![image](https://user-images.githubusercontent.com/8603325/52161571-36b9bb80-26c7-11e9-85b4-432535d35c24.png)


It can be modified in `tracker.php`
