### ISSUE TITLE
Call to undefined function PragmaRX\Tracker\ipv4_in_range()

### ISSUE THREAD

**Issue by Kolesar** [antonioribeiro/tracker#319]
Hi,

I made `composer update` last night and get error:

`Call to undefined function PragmaRX\Tracker\ipv4_in_range()`

What I should do for return my Laravel to up and running?

**Comment by namaljayathunga** [comment]
I am using v2.0.10 and I have same error.

**Comment by chrisballen** [comment]
Hey guys, I updated my composer.json and changed the tracker version to 3.2 and it worked for me.

`"pragmarx/tracker": "3.2",`

I also had to also rerun the create tracker tables which should only create one file then run the latest migration.  After doing this everything was working perfectly.  I hope this helps.

```
php artisan tracker:tables
php artisan migrate
```

Here is the migration it created for me 2017_06_20_311102_add_agent_name_hash.php

**Comment by antonioribeiro** [comment]
I just brought the helper back.
