### ISSUE TITLE
PHP Parse error

### ISSUE THREAD

**Issue by frankiecmk** [antonioribeiro/tracker#33]
There's an error with PHP Parse error:  syntax error, unexpected '$string' (T_VARIABLE) in /home/streamdl/public_html/vendor/pragmarx/support/src/helpers.php on line 767

Line 767 - yield $string;

'yield' only available in PHP version 5.5, below version PHP version 5.5 you will get above error.

**Comment by antonioribeiro** [comment]
Fixed a long time ago.
