### ISSUE TITLE
Auth with quard for stats  - Authentication required

### ISSUE THREAD

**Issue by pawelsome** [antonioribeiro/tracker#331]
Hey,
I have two roles on my page - users and admins. For users I am able to open stats panel but for admin i have a problem with a quard.
To get admin data i have to use auth()->guard('admin')->user();  instead of auth()->user();

Is there a way to authorize admin with quard to acces stats panel?

Now i have an error - Authentication required

**Comment by loveanimesh143** [comment]
I'm having the same issue with two roles in my website.
Help would be appreciated and if I'll get something I'll surely post.

**Comment by gabriel-cardoso** [comment]
Hi,

I have the same issue.

I only want to track my `User`s and not my `AdminUser`s who are respectively authenticated with `Auth::guard('user')->check()` and `Auth::guard('admin')->check()`.

What are our option ?

Should we add an config option for guards ?
