### ISSUE TITLE
log record generating twice

### ISSUE THREAD

**Issue by josephpaul** [antonioribeiro/tracker#35]
When page loads same log record generating twice. I tried loading different pages but every time its happening.
please check the screenshot of tracker_log
![tracker bug](https://cloud.githubusercontent.com/assets/3679805/4067720/19425730-2e31-11e4-97a2-0ee0001b13c2.png)

**Comment by antonioribeiro** [comment]
I need more information to try to understand and fix this. If it's still happening, please reopen.

**Comment by josephpaul** [comment]
The above table is screenshot of tracker_log table. when page load two records generating in the table. You can see the time different its 3 milliseconds. So when i calculating the page hits, i am getting  the double count.
Also i hope you will update laravel 5 compatible version soon. Eagerly waiting for that update.

**Comment by antonioribeiro** [comment]
Your application must be generating a second request. Can you reproduce it in a fresh application? If you can, please commit it to a public repository and I'll clone it to take a look.

**Comment by josephpaul** [comment]
Now i checked it again by installing fresh copy of tracker in laravel 4.2. And its ok now. Only generating single record at a time.  thank you for your support.
And also thank for updating laravel 5 compatible version, but i am getting error when installing tracker for laravel 5.  Everything goes fine until enabling tracker ("'enabled' => true"). After that i am getting an error.

Attached the screenshot of the error page. 

 


![index](https://cloud.githubusercontent.com/assets/3679805/6546274/cf14a570-c5a5-11e4-8a6e-966c9c7e250f.png)

**Comment by antonioribeiro** [comment]
The problem in Laravel 5 should be fixed now too.
