### ISSUE TITLE
Hide Warning Log - TRACKER (unable to track item): route tracker.stats.api.visits is not trackable.

### ISSUE THREAD

**Issue by adibnoh** [antonioribeiro/tracker#354]
Hi I got this warning in my log file

<img width="1401" alt="screenshot at dec 14 17-19-56" src="https://user-images.githubusercontent.com/8519799/33984664-651d5dc6-e0f3-11e7-9b4a-1b5c15974d28.png">

Can I hide this warning message because it doesn't necessary or did I did something wrong with my configuration that cause this warning message to appear

**Comment by ndberg** [comment]
Take a look in the config/tracker.php:

You can set log_untrackable_sessions = false.

And you can exclude routes you dont want do have tracked:
    'do_not_track_routes'       => [
        'tracker.stats.*',
    ],

**Comment by adibnoh** [comment]
Oh I don't realize that, thank you so much for helping me.
