### ISSUE TITLE
only Update "tracker_log" and " tracker_sessions" table

### ISSUE THREAD

**Issue by techmatevaibhav** [antonioribeiro/tracker#357]
Hello Team @antonioribeiro ,

I installed this plugin and its work but i have some doubt about how its working.
Just two table updates when i logged in and logged Out. 

I am testing in Localhost

below is the "Tracker_Sessions" table

![image](https://user-images.githubusercontent.com/20147143/34742218-681dbe3e-f553-11e7-9cbb-ea00c179ce69.png)

Below is the "Tracker_Log" table

![image](https://user-images.githubusercontent.com/20147143/34742256-8953e024-f553-11e7-944d-44649eddf897.png)

**Comment by FrankCumaio** [comment]
Hi there, im facing the same problem

**Comment by FrankCumaio** [comment]
I figure it out. As you are using localhost make sure you do the following modifications to your tracker file:
1 - make sure you enable the options that you want to track. Eg:
   'log_geoip' => false,

    /*
     * Do you wish to log the user agent?
     */
    'log_user_agents' => true,

    /*
     * Do you wish to log your users?
     */
    'log_users' => true,

    /*
     * Do you wish to log devices?
     */
    'log_devices' => true,

    /*
     * Do you wish to log languages?
     */
    'log_languages' => false,

    /*
     * Do you wish to log HTTP referers?
     */
    'log_referers' => false,

    /*
     * Do you wish to log url paths?
     */
    'log_paths' => true

2- Remove the localhost address (127.0.0.0/24) from "do_not_track_ips" option:

    /*
     * The Do Not Track Ips is used to disable Tracker for some IP addresses:
     *
     *     '127.0.0.1', '192.168.1.1'
     *
     * You can set ranges of IPs
     *     '192.168.0.1-192.168.0.100'
     *
     * And use net masks
     *     '10.0.0.0/32'
     *     '172.17.0.0/255.255.0.0'
     */
    'do_not_track_ips' => [
        '', /// range 127.0.0.1 - 127.0.0.255
    ],

Hope it helps you @techmatevaibhav

**Comment by techmatevaibhav** [comment]
@FrankCumaio  its work :-) Thank you for you help.
