### ISSUE TITLE
Laravel 5 migration errors

### ISSUE THREAD

**Issue by lukaszog** [antonioribeiro/tracker#358]
Hi, 
I have Laravel with version `"laravel/framework": "5.5.*",`. I'm download `tracker` and publish. When I type `php artisan migrate` I gets error:

![image](https://user-images.githubusercontent.com/5604018/34747711-ca60a6b0-f599-11e7-9990-5c055c118747.png)

My: database.php

```
   'tracker' => [
            'driver' => 'mysql',
            'host' => '127.0.0.1',
            'port' => env('DB_PORT', '3306'),
            'database' => 'testy',
            'username' => 'root',
            'password' => '',
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => 'InnoDB ROW_FORMAT=DYNAMIC',
        ],
```

Why?

**Comment by mbolukbasi** [comment]
i got the same error. Is there any solution?

**Comment by enasellithy** [comment]
i try this error fixed 
'tracker' => [
            'driver' => env('DB_CONNECTION','mysqli'),
            'host' => env('DB_HOST','127.0.0.1'),
            'database' => env('DB_TRACKER','elagy'),
            'username' => env('DB_USERNAME','tracker'),
            'password' => env('DB_PASSWORD','tracker'),
        ],
