### ISSUE TITLE
Don't work at laravel 5.6

### ISSUE THREAD

**Issue by magnum-ferox** [antonioribeiro/tracker#368]
Symfony\Component\Debug\Exception\FatalThrowableError  : Type error: Argument 5 passed to PragmaRX\Tracker\Tracker::__construct() must be an instance of Illuminate\Log\Writer, instance of Illuminate\Log\LogManager given, called in vendor\pragmarx\tracker\src\Vendor\Laravel\ServiceProvider.php on line 155

etc

**Comment by simonepozzobon** [comment]
[PR #367 ](https://github.com/antonioribeiro/tracker/pull/367)
btw I just changed in the namespace of `src/Tracker.php` from `use Illuminate\Log\Writer as Logger;` to `use Illuminate\Log\LogManager as Logger;`

**Comment by briansrepo** [comment]
@simonepozzobon that fix worked perfectly, thanks!

**Comment by antonioribeiro** [comment]
Fixed on 3.3.0.
