### ISSUE TITLE
How to Use custom table for Login

### ISSUE THREAD

**Issue by techmatevaibhav** [antonioribeiro/tracker#369]
Hey @antonioribeiro , 

  I am using my custom table for the login and i used my own custom guard.

Tracker plugin working fine but tracker_session table "user_id" values is blank.
![image](https://user-images.githubusercontent.com/20147143/36559486-321cda94-17dc-11e8-8dd4-f2bfc3c02417.png)

Below is my user table id
![image](https://user-images.githubusercontent.com/20147143/36559568-6452a7e6-17dc-11e8-8755-319d7442143e.png)

I did below settings in tracker.php but i think its wrong.
![image](https://user-images.githubusercontent.com/20147143/36559934-626fea00-17dd-11e8-9554-e0b50981b664.png)

**Comment by anuj509** [comment]
What is the solution?

**Comment by techmatevaibhav** [comment]
@anuj509  
![image](https://user-images.githubusercontent.com/20147143/36810718-8d644042-1c99-11e8-94f3-8c0277c46a0b.png)

I keep ioc_binding as it is "auth" and changed id to my custom table id. because using auth it take automatically guard and data.

Let me know if you have any question
