### ISSUE TITLE
Publishing not working in Laravel 5.4

### ISSUE THREAD

**Issue by devWaleed** [antonioribeiro/tracker#375]
I have tested this on 2 different projects on 2 different PCs. Publishing in a Laravel 5.4 through "php artisan vendor:publish --provider=PragmaRX\\Tracker\\Vendor\\Laravel\\ServiceProvider" doesn't work.

Migrations/Config are not copied. Using "pragmarx/tracker": "^3.2"

**Comment by devWaleed** [comment]
@antonioribeiro

**Comment by devWaleed** [comment]
I moved all migrations and config manually. It didn't work until I renamed config.php to tracker.php.

**Comment by toothbrush7777777** [comment]
You can do it like this:

```sh
php artisan vendor:publish --provider="PragmaRX\Tracker\Vendor\Laravel\ServiceProvider" --tag="config"
php artisan vendor:publish --provider="PragmaRX\Tracker\Vendor\Laravel\ServiceProvider" --tag="migrations"
```

**Comment by hamza-attiq** [comment]
> I has the same problem with the library running on Laravel 5.6. I figured out that you need to run these commands:
> 
> ```shell
> php artisan vendor:publish --provider="PragmaRX\Tracker\Vendor\Laravel\ServiceProvider" --tag="config"
> php artisan vendor:publish --provider="PragmaRX\Tracker\Vendor\Laravel\ServiceProvider" --tag="migrations"
> ```

I'm getting this error and already tried above commends
" There are no commands defined in the "tracker" namespace."

**Comment by toothbrush7777777** [comment]
That was nearly a year ago. I haven't used it recently.

**Comment by napestershine** [comment]
closing in favor of #418
