### ISSUE TITLE
Method PragmaRX\Tracker\Vendor\Laravel\Artisan\Tables::handle() does not exist

### ISSUE THREAD

**Issue by texnika01** [antonioribeiro/tracker#377]
error in  php artisan tracker:tables comands
on laravel 5.5

**Comment by houseofcoder** [comment]
This issue is solved here [https://github.com/antonioribeiro/tracker/issues/342](url)

**Comment by ipulrvs** [comment]
i have same problem too btw above url not exist 🥇

**Comment by texnika01** [comment]
Thank you for you help.
