### ISSUE TITLE
Don't get it working on Laravel 4.2

### ISSUE THREAD

**Issue by kremsy** [antonioribeiro/tracker#38]
I installed the Package on my Laravel 4.2 System, but as soon as I enable it "'enabled' => true,"
I get the following error: "Call to a member function connection() on a non-object".

Can't really find the cause and a solution to get it working.

Would be cool if you could help me out there.

**Comment by krambiorix** [comment]
Can you please update what solved your issue? I have can't get it started with 4.2 neither....

**Comment by kremsy** [comment]
Still not solved

**Comment by antonioribeiro** [comment]
Could you ping me on IRC? #laravel
