### ISSUE TITLE
Completely broken in Laravel 5.6 "use Illuminate\Log\Writer as Logger"

### ISSUE THREAD

**Issue by briansrepo** [antonioribeiro/tracker#384]
In Laravel 5.6 this needs to be changed to `use Illuminate\Log\LogManager as Logger;`
I can easily fix this locally but every time we deploy to staging / prod it breaks again because it's in the package code. Any idea how soon a fix will be released?

Also referenced here: https://github.com/antonioribeiro/tracker/issues/374
And here: https://github.com/antonioribeiro/tracker/issues/368

**Comment by antonioribeiro** [comment]
Fixed on 3.3.0.
