### ISSUE TITLE
Error while installing "doctrine/dbal v2.6.3 requires php ^7.1"

### ISSUE THREAD

**Issue by houseofcoder** [antonioribeiro/tracker#386]
I'm getting below error while installing Tracker plugin

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - doctrine/dbal v2.6.3 requires php ^7.1 -> your PHP version (7.0.18) does n
> ot satisfy that requirement.
>     - doctrine/dbal v2.6.2 requires php ^7.1 -> your PHP version (7.0.18) does n
> ot satisfy that requirement.
>     - doctrine/dbal v2.6.1 requires php ^7.1 -> your PHP version (7.0.18) does n
> ot satisfy that requirement.
>     - doctrine/dbal v2.6.0 requires php ^7.1 -> your PHP version (7.0.18) does n
> ot satisfy that requirement.
>     - pragmarx/tracker v3.3.0 requires doctrine/dbal ^2.6 -> satisfiable by doct
> rine/dbal[v2.6.0, v2.6.1, v2.6.2, v2.6.3].
>     - Installation request for pragmarx/tracker ^3.3 -> satisfiable by pragmarx/
> tracker[v3.3.0].

I guess it is because of recent commits in Tracker repository

**Comment by houseofcoder** [comment]
I found the work around that is to fake the php version in composer.json file as seen below..

![image](https://user-images.githubusercontent.com/33715705/37838464-f5efc734-2edd-11e8-8ec1-e1923b38b88c.png)

Not sure if it is good option. Is it fine @antonioribeiro ?

**Comment by grazinskis** [comment]
Same error here. Are the docs correct to say that the minimum PHP version is 5.3.7?

**Comment by napestershine** [comment]
Sorry we don't support PHP version less than 7. Upgrade your PHP version please. I will update docs too.
Thanks for feedback.
