### ISSUE TITLE
Call to a member function getStart() on a non-object

### ISSUE THREAD

**Issue by kanazaca** [antonioribeiro/tracker#39]
Hi installed tracker and when i run

$sessions = Tracker::sessions(60 * 24); // get sessions (visits) from the past day

or

$users = Tracker::users(60 * 24);

and more ....

i get this error:
D:\WebProjects\DaoLafoes\vendor\pragmarx\tracker\src\Vendor\Laravel\Models\Base.php
	
public function scopePeriod($query, $minutes, $alias = '')
	{
		$alias = $alias ? "$alias." : '';
 
		return $query
				->where($alias.'updated_at', '>=', $minutes->getStart())
				->where($alias.'updated_at', '<=', $minutes->getEnd());
	}

Can anyone help me ? pls Thanks

**Comment by antonioribeiro** [comment]
This was fixed ages ago. Closing. If you still have problems with this, please reopen.
