### ISSUE TITLE
The package does not work at all

### ISSUE THREAD

**Issue by Zoha** [antonioribeiro/tracker#393]
The package looks great.
But there's a problem for me and it's just that it does not work at all.
I created a Laravel project (on Windows - localhost) and I started installing the package, but when I want to run the first instance of the code, I'll get the following error : 

`"Trying to get property of non-object"`

And as I understand, there is a similar problem for a lot of others.
This is my code in `web.php` : 

```PHP
Route::get('/', function () {
    $visitor = Tracker::currentSession();
    var_dump( $visitor->client_ip );
    var_dump( $visitor->device->is_mobile );
});
```
in above code, I get null for client IP and the above error for is_mobile property. 

Do you know what the problem is?

**Comment by reza-akbari** [comment]
had the same problem on local machine. solved by allowing local IP (127.0.0.1) in _tracker.php_ file.
`
'do_not_track_ips' => [
        //'127.0.0.0/24', 
 ],
`

**Comment by mohamedsabil83** [comment]
Same problem here. Just the following was logged:
- tracker_routes
- tracker_route_paths
- tracker_route_path_parameters

**Comment by mohamedsabil83** [comment]
I remove it and re-install the package and move step-by-step and it's work fine. guess I forgot something not do in the first time.

@ZohaBanam check first the database is it contains data or not. If contain, paste here the full stack-tracing to check.

**Comment by ZohaBanam** [comment]
mohamedsabil83
I deleted it several times and installed it again. I did all the steps correctly, but it did not work again.
I'll reinstall it later and if the problem is still going on I'll do what you want
Thanks buddy

**Comment by mohamedsabil83** [comment]
Y.W.

**Comment by Zoha** [comment]
@napestershine I do not use it anymore :(
