### ISSUE TITLE
String data, right truncated: 1406 Data too long for column 'uuid' at row 1

### ISSUE THREAD

**Issue by michelmelo** [antonioribeiro/tracker#400]
I'm having the following error: I'm using mariadb
`SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'uuid' at row 1 (SQL: insert into `tracker_cookies` (`uuid`, `updated_at`, `created_at`) values (eyJpdiI6IjQ2YUpYUlA3TDhyOWwxcXRZaVZxekE9PSIsInZhbHVlIjoiS2x1VEZyWWpYWWhQdWt1NzJCTm83TXV3NGxSNkpjN1VpUjRRUGtLQXg0R2pkVFJZaTQ4dDM2U21Ia2x3OTMzZSIsIm1hYyI6ImFjYWVjNWNlOTZlMzg0ZjBjMWFhMmIyMzE3NzRkNmQ3OTUyNGY1M2U4M2U2NmJlZGEyODRmNGNmM2UzMzY5MGMifQ==, 2018-09-09 09:48:24, 2018-09-09 09:48:24))`

**Comment by Daisuke-sama** [comment]
Change to LONGTEXT type the type your column.

**Comment by CongAn** [comment]
> Change to LONGTEXT type the type your column.

1170 - BLOB/TEXT column 'uuid' used in key specification without a key length
