### ISSUE TITLE
tracker.php not exist 

### ISSUE THREAD

**Issue by mortezamoradi72** [antonioribeiro/tracker#413]
hi
**i want to install tracker but i can not find tracker.php in config folder?**
Laravel 5.7

composer require pragmarx/tracker                                                  Done
PragmaRX\Tracker\Vendor\Laravel\ServiceProvider::class,                  Done
'Tracker' => 'PragmaRX\Tracker\Vendor\Laravel\Facade',                  Done
php artisan vendor:publish --provider=PragmaRX\\Trac ....                Done
'use_middleware' => true,                                      There is not config/tracker.php !!!
'enabled' => true,                                                   There is not config/tracker.php !!!

**Comment by evgeniy2194** [comment]
Hi.
You should publish config. Try this:
`php artisan vendor:publish --provider="PragmaRX\Tracker\Vendor\Laravel\ServiceProvider" --tag="config"`

If it doesn't work, try just:
`php artisan vendor:publish --tag="config"`

**Comment by erfanhemmati** [comment]
@evgeniy2194 
php artisan vendor:publish --provider=PragmaRX\\Tracker\\Vendor\\Laravel\\ServiceProvider
This method dosent worked !!!!

**Comment by napestershine** [comment]
Closing, because another same issue opened on #418

**Comment by bapfnet** [comment]
You may return an example ID in the following function by

return 12345; // your example ID

https://github.com/antonioribeiro/tracker/blob/master/src/Services/Authentication.php

    public function getCurrentUserId()
    {
        if ($this->check()) {
            return $this->user()->{$this->config->get('authenticated_user_id_column')};
        }
    }

In my installation the Auth::check(); is not yet ready at the time the method is called. I don't know how the tracker is started.
