### ISSUE TITLE
Logging out sets tracker_session user_id to null?

### ISSUE THREAD

**Issue by ashniazi** [antonioribeiro/tracker#415]
Currently, when a User signs in, a tracker session gets created and that's great - however when a User logs out it sets `user_id` in `tracker_sessions` to `null`. This is problematic since I lose the ability to calculate the 'last active' attribute .

My log out code, it terminates the session which is what sets the `tracker_sessions` column `user_id` to null. 
```
    public function logout(Request $request)
    {
        $this->guard()->logout();

        $request->session()->invalidate();

        return $this->loggedOut($request) ?: redirect('/');
    }
```

The way I calculate last seen:

User Model
```
    public function session(){
        return $this->hasOne(Session::class);
    }

    public function getOnlineStatusAttribute(){
        $timeout = 3; //3 minutes
        if($this->session != null){
            $now = Carbon::now();
            $diff = $this->session->updated_at->diffInMinutes($now);
            return ($diff <= $timeout) ? true : false;
        }
    }
```

Thoughts?

**Comment by piep14** [comment]
@antonioribeiro please ^^

**Comment by mehdian-manesh** [comment]
add "logout" and "login" pages to the 'do_not_track_paths' in tracker config file.
like this:
`    
'do_not_track_paths' => [
        'api/*',
        'logout',
        'login',
    ],
`
