### ISSUE TITLE
Cant find tracker.php

### ISSUE THREAD

**Issue by erfanhemmati** [antonioribeiro/tracker#418]
I cant fint tracker.php in Laravel 5.7
where is tracker.php in laravel 5.7 ??

**Comment by ashniazi** [comment]
If the Tracker.php does not publish into your `app\config` folder try:
```
php artisan vendor:publish --provider="PragmaRX\Tracker\Vendor\Laravel\ServiceProvider" --tag="config"
```

It will now be present in `app/config/tracker.php`

Do keep in mind that this package currently(v3.3.0) isn't very stable on 5.7. There are some pull requests that fix some bugs, but even then there are some bugs. For example it was working during development for me but once I pushed to master and it was running on my deployment in production it bugged out.

**Comment by erfanhemmati** [comment]
@ashniazi 
Thanks for your help

**Comment by antonioribeiro** [comment]
@erfanhemmati, are you on Windows?

**Comment by ashniazi** [comment]
@antonioribeiro Hey - great job on the package. Can't speak for @erfanhemmati, but i encountered the same issue while being on Windows 10.

**Comment by napestershine** [comment]
Can you try on git bash, if you have installed on your system ?

**Comment by erfanhemmati** [comment]
@antonioribeiro 
yes , iam on windows 10 
how come ?

**Comment by napestershine** [comment]
somehow command is not working on windows command prompt. I am still working on it. You can use same command in git bash or a terminal similar to linux.

https://gitforwindows.org/
Just in case you need git bash
