### ISSUE TITLE
Requires user table?

### ISSUE THREAD

**Issue by KuenzelIT** [antonioribeiro/tracker#42]
Hey,
I'm currently testing tracker and I don't have any users to track. Not configured to track them of course. Can I disable that requirement somehow?

Error message:
Base table or view not found: 1146 Table 'db.users' doesn't exist (SQL: select * from `users` where `users`.`id` in (0)

Thanks!

**Comment by matyhaty** [comment]
Worked here also, close?

**Comment by antonioribeiro** [comment]
Closing it for now. Will reopen if needed.

**Comment by nonotest** [comment]
Having the same problem here.
I have a feeling it might be a problem with the DataTables extension when using multiple databases. 

Looks like its not selecting the correct database.

For example the session.php file , its looking for users

private function getSessions()
    {
        return $this
	            ->newQuery()
	            ->with('user')
		        ->with('device')
		        ->with('agent')
		        ->with('referer')
		        ->with('geoIp')
		        ->with('log')
		        ->with('cookie')
	            ->orderBy('updated_at', 'desc');
    }

For now i have replicated my users table in the statistics database

**Comment by arbabi2010** [comment]
Hi
How can i don't log some referees like admin pages???
