### ISSUE TITLE
pageViewsByCity 

### ISSUE THREAD

**Issue by usama-kabel** [antonioribeiro/tracker#424]
How can i get page views by city not country and period available start and end dates or all over data in DB?

**Comment by napestershine** [comment]
@usama-kabel you have data in DB now, So you can use it as you want.

**Comment by antonioribeiro** [comment]
@usama-kabel, unfortunately we cannot help much on issues related to specifics of your app, but if you look at the docs, you'll see that the app has a lot of methods you can use to start a query, search or count. For visits we have Sessions:

https://github.com/antonioribeiro/tracker#sessions-visits

It should return a collection which you can filter wherever you need to.
