### ISSUE TITLE
Access SB-admin template layouts

### ISSUE THREAD

**Issue by MikeDynamic** [antonioribeiro/tracker#429]
Hi, 

This is the first time that I am installing tracker and need some direction please. 

Not sure if this is a issue with my setup! 

I have a working DB that is tracking everything. I have the SB-admin installed and GEO-ip. 

I am not sure if I am supposed to create any routes for the Tracker or if this is done automatically as I would like to access the layouts in the screenshots (install guide) as a base to work from and understand the system. 

Could someone please point me in the right direction. 

Thank you

**Comment by napestershine** [comment]
Great! Just go to `/stats` and you should see it there

**Comment by MikeDynamic** [comment]
Ok, 

I ran php artisan route:list and I see that the routes are there. 
I am using Laravel 5.7 but I am getting a page saying user model misses admin property? 

Not sure what this is about as I do have and admin / webmaster level middleware

**Comment by napestershine** [comment]
In your user model just add this line
``` protected $connection = 'mysql';```

**Comment by MikeDynamic** [comment]
Thank you but it has not made a difference. 
It still says "User model misses admin property"

**Comment by napestershine** [comment]
Its mentioned in docs
![image](https://user-images.githubusercontent.com/8603325/52533514-1e841500-2d35-11e9-86ae-32f59ffa5111.png)

**Comment by MikeDynamic** [comment]
Are you meaning that I must add the getIsAdminAttribute() to the user model ? ie, the webmaster middleware? 

Thanks

**Comment by MikeDynamic** [comment]
I added it to the user model and I can access the stats now. Thank you...
