### ISSUE TITLE
Error: There are no commands defined in the "tracker" namespace.

### ISSUE THREAD

**Issue by AMAFsoft** [antonioribeiro/tracker#43]
I get that error when i trayed to create the UA Parser regex file using the command :  "php artisan tracker:updateparser".

**Comment by arunkspkm** [comment]
I get an error "PHP Fatal error:  Class 'PragmaRX\Tracker\Vendor\Laravel\ServiceProvider' not found in /var/www/storage/framework/compiled.php on line 6391"
