### ISSUE TITLE
cannot use tracker with different database

### ISSUE THREAD

**Issue by jalil1408** [antonioribeiro/tracker#435]
my app use its own db (app_db) with users table.
how can I use tracker with another database (tracker_db)?

**Comment by hafael** [comment]
+1

**Comment by hafael** [comment]
> my app use its own db (app_db) with users table.
> how can I use tracker with another database (tracker_db)?

https://github.com/antonioribeiro/tracker/issues/194#issuecomment-314147502

**Comment by hafael** [comment]
@antonioribeiro Que tal, por precaução, adicionar
`
/*
* ** IMPORTANT **
*   Change the user model to your own.
*  Explicitly define a connection from your user model
* protected $connection = 'mysql';
*/
'user_model' => 'Autum\Accounts\Models\User',
`

**Comment by napestershine** [comment]
@hafael Yes we can add.
