### ISSUE TITLE
Class 'Tracker' not found

### ISSUE THREAD

**Issue by tuvaergun** [antonioribeiro/tracker#45]
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_ERROR) 
Class 'Tracker' not found

why

Route::get('test', function() {

  $visitor = Tracker::currentSession();
return $visitor;

});

**Comment by doncadavona** [comment]
Still not working on my Laravel 5.1 app, thou I've added the service provider and the facade. The Tracker  class is still not found. I've already used:

`use PragmaRX\Tracker;`
`dd(Tracker::sessions());`
