### ISSUE TITLE
Method Yajra\DataTables\EloquentDataTable::edit_column does not exist.

### ISSUE THREAD

**Issue by nasirkhan** [antonioribeiro/tracker#452]
**Describe the bug**
Installed the package by following the doc. enabled the stats panel. When i tried to visit the stat dashboard, datatable was showing an error 'Method Yajra\DataTables\EloquentDataTable::edit_column does not exist.'

**Screenshots**
![Screenshot from 2019-07-20 14-31-44](https://user-images.githubusercontent.com/396987/61576371-1fe31600-aafb-11e9-8a6d-f1456b26a59e.png)

**System**
 - OS: Ubuntu
 - Browser Firefox

**Additional context**

**Comment by drbyte** [comment]
> datatable was showing an error 'Method Yajra\DataTables\EloquentDataTable::edit_column does not exist.'

That's because you have the yajra/datatables package installed, 
but this tracker package uses the no-longer-maintained https://github.com/bgultekin/laravel4-datatables-package which is hardcoded to the same `Datatables` alias.

Same issue as #431

**Comment by herytrie** [comment]
> 
> 
> **Describe the bug**
> Installed the package by following the doc. enabled the stats panel. When i tried to visit the stat dashboard, datatable was showing an error 'Method Yajra\DataTables\EloquentDataTable::edit_column does not exist.'
> 
> **Screenshots**
> ![Screenshot from 2019-07-20 14-31-44](https://user-images.githubusercontent.com/396987/61576371-1fe31600-aafb-11e9-8a6d-f1456b26a59e.png)
> 
> **System**
> 
>     * OS: Ubuntu
> 
>     * Browser Firefox
> 
>     * Version [e.g. 22]
> 
> 
> **Additional context**
> Add any other context about the problem here.

open this file from your laravel project :
vendor\pragmarx\tracker\src\Vendor\Laravel\Controllers\Stats.php

and replace all this "edit_column" with "editColumn"
and replace all too "add_column" with "addColumn"

inSha Allah it's work...

**Comment by antonioribeiro** [comment]
Fixed.
