### ISSUE TITLE
v3.4.0 broken due to pragmarx/support 0.9.0

### ISSUE THREAD

**Issue by drbyte** [antonioribeiro/tracker#464]
**Describe the bug**
pragmarx/tracker 3.4.0 depends on pragmarx/support 0.9.0
In pragmarx/support 0.9.0 [the `helpers.php` functions file was altered](https://github.com/antonioribeiro/support/pull/15) to remove the `isLaravel5()` function ... but it's used by this tracker package in 3 locations:

https://github.com/antonioribeiro/tracker/blob/bd7bea39918f7a21d363d704c0c152208307b013/src/Vendor/Laravel/Artisan/Tables.php#L70-L72

https://github.com/antonioribeiro/tracker/blob/bd7bea39918f7a21d363d704c0c152208307b013/src/Vendor/Laravel/ServiceProvider.php#L84-L86

https://github.com/antonioribeiro/tracker/blob/bd7bea39918f7a21d363d704c0c152208307b013/src/Vendor/Laravel/ServiceProvider.php#L396-L414

<img width="886" alt="Screen Shot 2019-09-10 at 9 58 40 PM" src="https://user-images.githubusercontent.com/404472/64662397-53189600-d416-11e9-9fa2-70b793fa870b.png">

**Comment by drbyte** [comment]
Temporary workaround is to manually force pragmarx/support to install an older version, with:

`composer require pragmarx/support:"^0.8.8"`

**Comment by antonioribeiro** [comment]
Will fix this as soon as possible.
Thanks for reporting it
-- 
Antonio Carlos Ribeiro
acr@antoniocarlosribeiro.com

Enviado do meu iPhone

**Comment by antonioribeiro** [comment]
Fixed.
