### ISSUE TITLE
Expose getCurrentLogId from the logRepository within Tracker singleton

### ISSUE THREAD

**Issue by Triztan** [antonioribeiro/tracker#465]
Any chance to expose the getCurrentLogId function from the logRepository directly from the Tracker singleton?

I know it's pretty simple to just hook it from the IoC but as you are already using your main Tracker class as an entry point for all the features of the package i think this could help development process.

My case:
Wanted to "extend" the functionality of the package including new tables/models, for that i wanted to just wrap your Tracker singleton and keep using features from there.
As i didn't have any way to get the current log entry id i had two options:

* Replace your Tracker class with my own one and implement the function.
* Hook from the IoC Container the tracker.repositories binding(the manager) and keep it also inside of my wrapper.

I took the first one because i didn't want to have too many injections from the container for just one feature.

Love the package, it's impressive how many features you can have in your project with just a simple package include. Keep the good work up!

**Comment by antonioribeiro** [comment]
Doesn't `Tracker::getLogger()->getCurrentLogId()` work for you?

**Comment by Triztan** [comment]
getLogger is a private method if i'm not wrong, so this is also not an option

**Comment by antonioribeiro** [comment]
Yeah, sorry, you are right. Just made some of those public, including getLogger.
