### ISSUE TITLE
Allowed memory size exhausted when installing tracker package with composer

### ISSUE THREAD

**Issue by MrSrsen** [antonioribeiro/tracker#467]
**Describe the bug**
I wanted to install `pragmarx/tracker` package and installation process crashed with exception `PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted`.

**To Reproduce**
```
martin@martin-mbp:~/PhpstormProjects/smart-finance$ php7.2 composer.phar require pragmarx/tracker
Using version ^3.4 for pragmarx/tracker
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 67108864 bytes) in phar:///Users/martin/PhpstormProjects/smart-finance/composer.phar/src/Composer/DependencyResolver/Solver.php on line 223

Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 67108864 bytes) in phar:///Users/martin/PhpstormProjects/smart-finance/composer.phar/src/Composer/DependencyResolver/Solver.php on line 223

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.
```

**Expected behavior**
I am able to install `pragmarx/tracker` package.

**System**
 - OS: MacOS 10.4.5
 - PHP 7.2.16, Laravel 5.5.40, Composer 1.8.5

I tried this on PC with Windows 10 with PHP 7.2 and result was the same.

**Comment by drbyte** [comment]
I get this too.

Temporary workaround: specify memory limit on command-line when running composer:
`COMPOSER_MEMORY_LIMIT=-1 composer update`
or
`COMPOSER_MEMORY_LIMIT=-1 composer install pragmarx/tracker`

**Comment by MazzMazz** [comment]
I get the same with PHP 7.4, Laravel 6 on macOS 10.15.1 & composer 1.9.3

`COMPOSER_MEMORY_LIMIT=-1 composer install pragmarx/tracker` made it work (temporarily)

**Comment by MrSrsen** [comment]
I think that this issue is not relevant anymore.
