### ISSUE TITLE
Laravel 6.0 support

### ISSUE THREAD

**Issue by pawel-marciniak** [antonioribeiro/tracker#470]
**Describe the bug**
Changelog of version 3.4.0 says that support for Laravel 6 is added but in  `src/Vendor/Laravel/Support/Session.php` Input facede is used, which is not present in Laravel 6.0.

**To Reproduce**
1. Try to enter stats panel.
2. Error `Class 'Illuminate\Support\Facades\Input' not found` occured.

**Expected behavior**
Working stats panel.

**System**
 - OS: Mac OS 10.14.6
 - Browser: Chrome
 - Version 77

**Comment by eadortsu** [comment]
I hacked a [fix](https://github.com/eadortsu/tracker/tree/fix-laravel6) for laravel 6.
Try it out if it may help.

**Comment by antonioribeiro** [comment]
@eadortsu, your patch was merged. Thank you!
