### ISSUE TITLE
Class tracker does not exist ?

### ISSUE THREAD

**Issue by suryatresna** [antonioribeiro/tracker#50]
ReflectionException (-1)
Class tracker does not exist

Why ..?
use PragmaRX\Tracker\Vendor\Laravel\Facade as Tracker;
class HomeController extends BaseController {
    public function showVisitor()
    {
        $visitor = Tracker::currentSession();
        return $visitor;
    }
}

**Comment by saifulss** [comment]
@antonioribeiro I'm trying to use this for Laravel 5.5 with the usual Laravel IDE Helper package by barryvdh. Trying to generate the helper file causes this same error to appear.

`Exception: Class tracker does not exist
Skipping \PragmaRX\Tracker\Vendor\Laravel\Facade.

Exception: Class tracker does not exist
Skipping \PragmaRX\Tracker\Vendor\Laravel\Facade.
`

Sorry, unfamiliar with the etiquette. Should I open a new issue?
