### ISSUE TITLE
Argument 1 passed to UAParser\Parser::parse()

### ISSUE THREAD

**Issue by robertnicjoo** [antonioribeiro/tracker#503]
**Describe the bug**
When I try to run migration command I get this error

```
  Argument 1 passed to UAParser\Parser::parse() must be of the type string, null given, called in C:\laragon\www
  \mysitetesting\vendor\pragmarx\tracker\src\Support\UserAgentParser.php on line 25
```

Any idea?

**Comment by doncadavona** [comment]
There's a temporary solution at [StackOverflow](https://stackoverflow.com/questions/61553676/argument-1-passed-to-uaparser-parserparse-must-be-of-the-type-string-null-g). But it should be solved by the package.

**Comment by antonioribeiro** [comment]
New version tagged. You should be able to set a default user agent via config now. And it will pass a '' instead of null. Sorry for the delay.
