### ISSUE TITLE
Incompatible with most recent version of SB Admin 2

### ISSUE THREAD

**Issue by ramirezd42** [antonioribeiro/tracker#53]
Hi,

I noticed that the commands for downloading SB Admin 2 in your installation guide reference an old location that no longer exists. I downloaded the most recent version from their website (http://startbootstrap.com/template-overviews/sb-admin-2/) but the file names for the included JQuery library and font awesome css filles have changed slightly in the newer version, which breaks the stats views.

The references to these files would ideally be customizable in the config for Tracker I think, but do you know which version of SB Admin 2 you built the views around as a fix for now?

**Comment by arall** [comment]
I have the same problem. I have tried to adapt all the assets routes, and some views doesn't work (js errors I guess).

**Comment by antonioribeiro** [comment]
Just tagged 0.7.4. It's now compatible.
