### ISSUE TITLE
Requirements are not Satisfied

### ISSUE THREAD

**Issue by abbasmashaddy72** [antonioribeiro/tracker#536]
**Describe the bug**
Does not satisfy the requirement

**To Reproduce**
1. PHP 8.0, Laravel 8.x
2. composer require pragmarx/tracker
3. Output:
'Problem 1
    - pragmarx/tracker v4.0.x-dev requires php ^7.0 -> your php version (8.0.6) does not satisfy that requirement.
    - pragmarx/tracker[v4.0.0, ..., v4.0.1] require doctrine/dbal ^2.6 -> found doctrine/dbal[v2.6.0, ..., 2.13.x-dev] but the package is fixed to 3.1.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires pragmarx/tracker ^4.0 -> satisfiable by pragmarx/tracker[v4.0.0, v4.0.1, v4.0.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.'
4. When installing with -W:
'Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+abbasmashaddy72+2021-06-08+1656
to retrieve a token. It will be stored in "/home/abbasmashaddy72/.config/composer/auth.json" for future use by Composer.
Token (hidden):'

**Expected behavior**
Normal Installations without Errors

**Screenshots**
No Screen Shots

**System**
 - OS: Manjaro Linux
 - Browser: Chrome
 - Version: 90.0.4430.212

**Additional context**
Problem occurred in console with installing

**Comment by mintalicious** [comment]
Has anyone solved this issue or found a workaround for it?
In my case, the dependencies for laravel/framework (required: ^5.5, installed: ^8.40) and doctrine/dbal (required: ^2.6, installed: ^3.1) don't seem to be right when trying to install pragmarx/tracker.
When using specific version 4.0.1, only doctrine/dbal dependency is unsolved.

**Comment by fzahid001** [comment]
Has anyone solved this issue.. As I am tying to install the package on laravel 8 and getting the exact same issue

**Comment by moacdev** [comment]
1. Delete your project **vendor** file
2. Remove **"pragmarx/tracker":^xx** line from your composer.json
3. Delete also the **composer.lock** file
2. Run **composer i**
3. then run **composer require pragmarx/tracker**

This worked fine for me

**Comment by bhargav960143** [comment]
Solved.

Issue attached
![issue](https://user-images.githubusercontent.com/4817599/132984084-e079f542-65a3-4ebe-bc27-531d8c030509.png)


Update your composer with following line
"doctrine/dbal": "^2.6",

![solution](https://user-images.githubusercontent.com/4817599/132984112-0248e7f2-a1ed-4147-8ea9-9fb891e988b6.png)

composer require pragmarx/tracker -W

**Comment by moacdev** [comment]
> Solved.
> 
> Issue attached
> ![issue](https://user-images.githubusercontent.com/4817599/132984084-e079f542-65a3-4ebe-bc27-531d8c030509.png)
> 
> Update your composer with following line
> "doctrine/dbal": "^2.6",
> 
> ![solution](https://user-images.githubusercontent.com/4817599/132984112-0248e7f2-a1ed-4147-8ea9-9fb891e988b6.png)
> 
> composer require pragmarx/tracker -W

Nice

**Comment by Iheanyi001** [comment]
Laravel 9 and php 8.1 is not supported

**Comment by JayeshKathrotiya** [comment]
Has anyone solved this issue? As I am trying to install the package on laravel 9 and getting the exact same issue
