### ISSUE TITLE
No tables are being logged to except for the tracker_sessions table

### ISSUE THREAD

**Issue by peterlentine** [antonioribeiro/tracker#54]
I went through the guide for installing tracker, but for some reason the only table being logged to is tracker_sessions.

I enabled all of trackers logging features, demonstrated in the config file below. I have tried adding all tables to my applications database and creating a separate database just for tracker. Both of these configurations are yielding the same results. No matter how I change my configuration the only table being written to is the tracker_sessions table.
__________________________________________________________________
/app/vendor/pragmarx/tracker/src/config/config.php
<?php
/**
 * Part of the Tracker package.
 *
 * NOTICE OF LICENSE
 *
 * Licensed under the 3-clause BSD License.
 *
 * This source file is subject to the 3-clause BSD License that is
 * bundled with this package in the LICENSE file.  It is also available at
 * the following URL: http://www.opensource.org/licenses/BSD-3-Clause
 *
 * @package    Tracker
 * @author     Antonio Carlos Ribeiro @ PragmaRX
 * @license    BSD License (3-clause)
 * @copyright  (c) 2013, PragmaRX
 * @link       http://pragmarx.com
 */

return [

	/**
	 * Enable it?
	 */
	'enabled' => true,

	/**
	 * Robots should be tracked?
	 */
	'do_not_track_robots' => true,

	/**
	 * Which environments are not trackable?
	 */
	'do_not_track_environments' => [
		// defaults to none
	],

	/**
	 * Which routes names are not trackable?
	 */
	'do_not_track_routes' => [
		'tracker.stats.*',
	],

	/**
	 * The Do Not Track Ips is used to disable Tracker for some IP addresses:
	 *
	 *     '127.0.0.1', '192.168.1.1'
	 *
	 * You can set ranges of IPs
	 *     '192.168.0.1-192.168.0.100'
	 *
	 * And use net masks
	 *     '10.0.0.0/32'
	 *     '172.17.0.0/255.255.0.0'
	 */
	'do_not_track_ips' => [
		'127.0.0.0/24' /// range 127.0.0.1 - 127.0.0.255
	],

	/**
	 * Log every single access?
	 *
	 * The log table can become huge if your site is popular, but...
	 *
	 * Log table is also responsible for storing information on:
	 *
	 *    - Routes and controller actions accessed
	 *    - HTTP method used (GET, POST...)
	 *    - Error log
	 *    - URL queries (including values)
	 */
	'log_enabled' => true,

	/**
	 * Log SQL queries?
	 *
	 * Log must be enabled for this option to work.
	 */
	'log_sql_queries' => true,

	/**
	 * If you prefer to store Tracker data on a different database or connection,
	 * you can set it here.
	 *
	 * To avoid SQL queries log recursion, create a different connection for Tracker,
	 * point it to the same database (or not) and forbid logging of this connection in
	 * do_not_log_sql_queries_connections.
	 */
	'connection' => 'tracker',

	/**
	 * Forbid logging of SQL queries for some connections.
	 *
	 * To avoid recursion, you better ignore Tracker connection here.
	 *
	 * Please create a separate database connection for Tracker. It can hit
	 * the same database of your application, but the connection itself
	 * has to have a different name, so the package can ignore its own queries
	 * and avoid recursion.
	 *
	 */
	'do_not_log_sql_queries_connections' => [
		'tracker'
	],

	/**
	 * Also log SQL query bindings?
	 *
	 * Log must be enabled for this option to work.
	 */
	'log_sql_queries_bindings' => true,

	/**
	 * Log events?
	 */
	'log_events' => true,

	/**
	 * Which events do you want to log exactly?
	 */
	'log_only_events' => [
		// defaults to logging all events
	],

	/**
	 * What are the names of the id columns on your system?
	 *
	 * 'id' is the most common, but if you have one or more different,
	 * please add them here in your preference order.
	 */
	'id_columns_names' => [
		'id'
	],
	/**
	 * Do not log events for the following patterns.
	 * Strings accepts wildcards:
	 *
	 *    eloquent.*
	 *
	 */
	'do_not_log_events' => [
		'illuminate.log',
		'eloquent.*',
		'router.*',
		'composing: *',
		'creating: *',
	],

	/**
	 * Do you wish to log Geo IP data?
	 *
	 * You will need to install the geoip package
	 *
	 *     composer require "geoip/geoip":"~1.14"
	 *
	 * And remove the PHP module
	 *
	 *     sudo apt-get purge php5-geoip
	 *
	 */
	'log_geoip' => true,

	/**
	 * Do you wish to log the user agent?
	 */
	'log_user_agents' => true,

	/**
	 * Do you wish to log your users?
	 */
	'log_users' => true,

	/**
	 * Do you wish to log devices?
	 */
	'log_devices' => true,

	/**
	 * Do you wish to log HTTP referers?
	 */
	'log_referers' => true,

	/**
	 * Do you wish to log url paths?
	 */
	'log_paths' => true,

	/**
	 * Do you wish to log url queries and query arguments?
	 */
	'log_queries' => true,

	/**
	 * Do you wish to log routes and route parameters?
	 */
	'log_routes' => true,

	/**
	 * Log errors and exceptions?
	 */
	'log_exceptions' => true,

	/**
	 * A cookie may be created on your visitor device, so you can have information
	 * on everything made using that device on your site.	 *
	 */
	'store_cookie_tracker' => true,

	/**
	 * If you are storing cookies, you better change it to a name you of your own.
	 */
	'tracker_cookie_name' => 'please_change_this_cookie_name',

	/**
	 * Internal tracker session name.
	 */
    'tracker_session_name' => 'tracker_session',

	/**
	 * ** IMPORTANT **
	 *   Change the user model to your own.
	 */
	'user_model' => 'PragmaRX\Tracker\Vendor\Laravel\Models\User',

	/**
	 * You can use your own model for every single table Tracker has.
	 */

    'session_model' => 'PragmaRX\Tracker\Vendor\Laravel\Models\Session',

    'log_model' => 'PragmaRX\Tracker\Vendor\Laravel\Models\Log',

	'path_model' => 'PragmaRX\Tracker\Vendor\Laravel\Models\Path',

	'query_model' => 'PragmaRX\Tracker\Vendor\Laravel\Models\Query',

	'query_argument_model' => 'PragmaRX\Tracker\Vendor\Laravel\Models\QueryArgument',

	'agent_model' => 'PragmaRX\Tracker\Vendor\Laravel\Models\Agent',

    'device_model' => 'PragmaRX\Tracker\Vendor\Laravel\Models\Device',

    'cookie_model' => 'PragmaRX\Tracker\Vendor\Laravel\Models\Cookie',

	'domain_model' => 'PragmaRX\Tracker\Vendor\Laravel\Models\Domain',

	'referer_model' => 'PragmaRX\Tracker\Vendor\Laravel\Models\Referer',

	'route_model' => 'PragmaRX\Tracker\Vendor\Laravel\Models\Route',

	'route_path_model' => 'PragmaRX\Tracker\Vendor\Laravel\Models\RoutePath',

	'route_path_parameter_model' => 'PragmaRX\Tracker\Vendor\Laravel\Models\RoutePathParameter',

	'error_model' => 'PragmaRX\Tracker\Vendor\Laravel\Models\Error',

	'geoip_model' => 'PragmaRX\Tracker\Vendor\Laravel\Models\GeoIp',

	'sql_query_model' => 'PragmaRX\Tracker\Vendor\Laravel\Models\SqlQuery',

	'sql_query_binding_model' => 'PragmaRX\Tracker\Vendor\Laravel\Models\SqlQueryBinding',

	'sql_query_binding_parameter_model' => 'PragmaRX\Tracker\Vendor\Laravel\Models\SqlQueryBindingParameter',

	'sql_query_log_model' => 'PragmaRX\Tracker\Vendor\Laravel\Models\SqlQueryLog',

	'connection_model' => 'PragmaRX\Tracker\Vendor\Laravel\Models\Connection',

	'event_model' => 'PragmaRX\Tracker\Vendor\Laravel\Models\Event',

	'event_log_model' => 'PragmaRX\Tracker\Vendor\Laravel\Models\EventLog',

	'system_class_model' => 'PragmaRX\Tracker\Vendor\Laravel\Models\SystemClass',

	/**
	 * Laravel internal variables on user authentication and login.
	 */
	'authentication_ioc_binding' => 'auth', // defaults to 'auth' in Illuminate\Support\Facades\Auth

    'authenticated_check_method' => 'check', // to Auth::check()

    'authenticated_user_method' => 'user', // to Auth::user()

    'authenticated_user_id_column' => 'id', // to Auth::user()->id

    'authenticated_user_username_column' => 'email', // to Auth::user()->email

	/**
	 * Laravel Alias, create one? Which name?
	 */
	'create_tracker_alias' => true,

	'tracker_alias' => 'Tracker',

	/**
	 * Enable the Stats Panel?
	 */
	'stats_panel_enabled' => true,

	/**
	 * Stats Panel routes before filter
	 *
	 * You better drop an 'auth' filter here.
	 */
	'stats_routes_before_filter' => '',

	/**
     * Stats Panel template path
     */
    'stats_template_path' => '/templates/sb-admin-2',

    /**
     * Stats Panel base uri.
     *
     * If your site url is http://wwww.mysite.com, then your stats page will be:
     *
     *    http://wwww.mysite.com/stats
     *
     */
    'stats_base_uri' => 'stats',

    /**
     * Stats Panel layout view
     */
    'stats_layout' => 'pragmarx/tracker::layout',

    /**
     * Stats Panel controllers namespace
     */
    'stats_controllers_namespace' => 'PragmaRX\Tracker\Vendor\Laravel\Controllers',
];

**Comment by QuantumSuicide** [comment]
I'm currently having the same issue. Did you figure it out?

**Comment by rtconner** [comment]
I had to remove 127.0.0.0/24 from the do_not_track_ips option to get logging to work on my dev box.

**Comment by peterlentine** [comment]
@QuantumSuicide  No I haven't.
@rtconner  I tried removing that no luck. Thanks for the suggestion.

**Comment by antonioribeiro** [comment]
Are you still experiencing this on master? Does it happen on "~1.0@dev" too (laravel5 branch)? Please comment here and I'll reopen.
