### ISSUE TITLE
The installation is smooth, but i just can't get any track data

### ISSUE THREAD

**Issue by woodytang** [antonioribeiro/tracker#55]
My app is being developed in local environment, I noticed the several options should be enabled in config.php, but I just can't get it to work to show anything.

My controller code:
public function show($id){

        $post=Post::with('category')->findOrFail($id);

        $rootmenus = Menu::roots()->get();

        $views=Tracker::logByRouteName('posts.show')
            ->where(function($query)
            {
                $query
                    ->where('parameter', 'id')
                    ->where('value', '$id');
            })
            ->count();

        //dd($views);
        return View::make('front.posts.show',compact('post','rootmenus','views'));
    }

$views always show 0..

**Comment by matyhaty** [comment]
Have you checked the the database tables to see if things are in there

Have you removed the local IPs not being tracked in the config if running locally?

**Comment by rtconner** [comment]
I had to remove 127.0.0.0/24 from the do_not_track_ips option to get logging to work on my dev box.

**Comment by antonioribeiro** [comment]
This one should fix this: https://github.com/antonioribeiro/tracker/commit/1f86e5646a70e96e47630d001a02bd6988c86436
