### ISSUE TITLE
Constant ENCODING in class Symfony\Component\Yaml\Unescaper is deprecated since version 2.5 and will be removed in 3.0.

### ISSUE THREAD

**Issue by globsecure** [antonioribeiro/tracker#56]
Errors on execute:

php artisan tracker:updateparser

--

[2015-01-07 12:09:06] local.ERROR: exception 'ErrorException' with message 'Constant ENCODING in class Symfony\Component\Yaml\Unescaper is deprecated since version 2.5 and will be removed in 3.0.' in C:\Desenvolvimento\Servidores\Web\Apache\htdocs\perola\vendor\sy
mfony\yaml\Symfony\Component\Yaml\Deprecated\Unescaper.php:5 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleError(16384, 'Constant ENCODI...', 'C:\Desenvolvime...', 5, Array) #1 C:\Desenvolvimento\Servidores\Web\Apache\htdocs\perola\vendo
r\symfony\yaml\Symfony\Component\Yaml\Deprecated\Unescaper.php(5): trigger_error('Constant ENCODI...', 16384) #2 C:\Desenvolvimento\Servidores\Web\Apache\htdocs\perola\vendor\composer\ClassLoader.php(386): include('C:\Desenvolvime...') #3 C:\Desenvolvimento\Servid
ores\Web\Apache\htdocs\perola\vendor\composer\ClassLoader.php(278): Composer\Autoload\includeFile('C:\Desenvolvime...') #4 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\Compone...') #5 C:\Desenvolvimento\Servidores\Web\Apache\htdocs\perola
\vendor\symfony\yaml\Symfony\Component\Yaml\Inline.php(263): spl_autoload_call('Symfony\Compone...') #6 C:\Desenvolvimento\Servidores\Web\Apache\htdocs\perola\vendor\symfony\yaml\Symfony\Component\Yaml\Inline.php(212): Symfony\Component\Yaml\Inline::parseQuotedSca
lar(''(HbbTV)/(\d+)\...', 0) #7 C:\Desenvolvimento\Servidores\Web\Apache\htdocs\perola\vendor\symfony\yaml\Symfony\Component\Yaml\Inline.php(71): Symfony\Component\Yaml\Inline::parseScalar(''(HbbTV)/(\d+)\...', NULL, Array, 0, true, Array) #8 C:\Desenvolvimento\Se
rvidores\Web\Apache\htdocs\perola\vendor\symfony\yaml\Symfony\Component\Yaml\Parser.php(462): Symfony\Component\Yaml\Inline::parse(''(HbbTV)/(\d+)\...', false, false, false, Array) #9 C:\Desenvolvimento\Servidores\Web\Apache\htdocs\perola\vendor\symfony\yaml\Symfo
ny\Component\Yaml\Parser.php(224): Symfony\Component\Yaml\Parser->parseValue(''(HbbTV)/(\d+)\...', false, false, false) #10 C:\Desenvolvimento\Servidores\Web\Apache\htdocs\perola\vendor\symfony\yaml\Symfony\Component\Yaml\Parser.php(114): Symfony\Component\Yaml\Pa
rser->parse('regex: '(HbbTV)...', false, false, false) #11 C:\Desenvolvimento\Servidores\Web\Apache\htdocs\perola\vendor\symfony\yaml\Symfony\Component\Yaml\Parser.php(216): Symfony\Component\Yaml\Parser->parse('- regex: '(HbbT...', false, false, false) #12 C:\Des
envolvimento\Servidores\Web\Apache\htdocs\perola\vendor\symfony\yaml\Symfony\Component\Yaml\Yaml.php(71): Symfony\Component\Yaml\Parser->parse('user_agent_pars...', false, false) #13 C:\Desenvolvimento\Servidores\Web\Apache\htdocs\perola\vendor\pragmarx\ua-parser\
php\src\UAParser\Util\Converter.php(53): Symfony\Component\Yaml\Yaml::parse('user_agent_pars...') #14 C:\Desenvolvimento\Servidores\Web\Apache\htdocs\perola\vendor\pragmarx\tracker\src\Vendor\Laravel\Artisan\UpdateParser.php(48): UAParser\Util\Converter->convertSt
ring('user_agent_pars...', false) #15 C:\Desenvolvimento\Servidores\Web\Apache\htdocs\perola\vendor\laravel\framework\src\Illuminate\Console\Command.php(108): PragmaRX\Tracker\Vendor\Laravel\Artisan\UpdateParser->fire() #16 C:\Desenvolvimento\Servidores\Web\Apache
\htdocs\perola\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(241): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #17 C:\Desenvolvimento\Servidor
es\Web\Apache\htdocs\perola\vendor\laravel\framework\src\Illuminate\Console\Command.php(96): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #18 C:\Desenvolvi
mento\Servidores\Web\Apache\htdocs\perola\vendor\symfony\console\Symfony\Component\Console\Application.php(887): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #19 C:\Desen
volvimento\Servidores\Web\Apache\htdocs\perola\vendor\symfony\console\Symfony\Component\Console\Application.php(191): Symfony\Component\Console\Application->doRunCommand(Object(PragmaRX\Tracker\Vendor\Laravel\Artisan\UpdateParser), Object(Symfony\Component\Console
\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #20 C:\Desenvolvimento\Servidores\Web\Apache\htdocs\perola\vendor\symfony\console\Symfony\Component\Console\Application.php(121): Symfony\Component\Console\Application->doRun(Object(Symfony
\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #21 C:\Desenvolvimento\Servidores\Web\Apache\htdocs\perola\artisan(59): Symfony\Component\Console\Application->run() #22 {main} [] []

  [ErrorException]
  Constant ENCODING in class Symfony\Component\Yaml\Unescaper is deprecated since version 2.5 and will be removed in 3.0.

tracker:updateparser [--database[="..."]] [query1] ... [queryN]

**Comment by antonioribeiro** [comment]
Ua-Parser is not using Unescaper directly. Symfony is using its own deprecated class:

https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Yaml/Inline.php#L263

Issue opened on Symfony: https://github.com/symfony/symfony/issues/13306.

**Comment by antonioribeiro** [comment]
I'm now forcing ua-parser to not install symfony/yaml 2.7 and stick to be up to 2.6. Worked here, please do a test on your end.

**Comment by fabpot** [comment]
Should be fixed when symfony/symfony#13325 will be merged, sorry for the inconvenience.

**Comment by fabpot** [comment]
Should be fixed now.

**Comment by antonioribeiro** [comment]
Version constraint removed. Tested. All good! Closing.

Thanks @fabpot.
