### ISSUE TITLE
Cannot call abstract method Illuminate\Support\ServiceProvider::register()

### ISSUE THREAD

**Issue by canaveensetia** [antonioribeiro/tracker#58]
Hello,

Thanks for this wonderful package. After installing, I am getting "Cannot call abstract method Illuminate\Support\ServiceProvider::register()" error. I tried using "dev-master" and "0.7.*".

It is coming from vendor\pragmarx\tracker\src\Vendor\Laravel\ServiceProvider.php file and line no.  97 i.e. parent::register();

Please let me know if you need any other information.

Regards,
Naveen Setia

**Comment by antonioribeiro** [comment]
Should be fixed by last changes. Also I installed it again today and had no problem. Please comment here if you receive this error again and I'll try to understand it. Thank you.
