### ISSUE TITLE
ErrorException: Undefined index: app (when using phpunit)

### ISSUE THREAD

**Issue by rtconner** [antonioribeiro/tracker#59]
Running phpunit with tracker installed and received the message below.

```
ErrorException: Undefined index: app

vendor/pragmarx/tracker/src/Vendor/Laravel/Models/Base.php:37
```
Error persists even with 'do_not_track_environments' => ['testing'] set

**Comment by antonioribeiro** [comment]
Fixed by https://github.com/antonioribeiro/tracker/commit/ce2e46878cb0695d36174b2075ccd79363084e78.
