### ISSUE TITLE
Unzip sb-admin 2 sources

### ISSUE THREAD

**Issue by phuclh** [antonioribeiro/tracker#60]
I can not unzip sb-admin 2. Maybe the archive is corrupt. I got a message:

```error
End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of sba2.zip or
        sba2.zip.zip, and cannot find sba2.zip.ZIP, period.
```

**Comment by ganey** [comment]
Did you download with wget? I had to download the file manually from the startbootstrap sbadmin2 page.

The file from the download link is https://github.com/IronSummitMedia/startbootstrap-sb-admin-2/archive/v1.0.5.zip

**Comment by antonioribeiro** [comment]
Closing as you have not answered this.
