### ISSUE TITLE
Call to a member function parameters() on a non-object

### ISSUE THREAD

**Issue by pranshu792** [antonioribeiro/tracker#63]
route_path_id is saving as NULL in trackerLog Table?

foreach ($route->current()->parameters() as $parameter => $value)
			{

**Comment by joy014** [comment]
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_ERROR) 
Call to a member function parameters() on a non-object

In vendor\tragmarx\tracker\src\data\RepositoryManager.php, line 375.

When the page is refreshed, it works correctly, 2nd time onwards.
Upon inspection, we found out that route_path_id is saving as NULL in trackerLog Table for the 1st page hit (1st ever hit on a route, after installing tracker)

If we replace if($created) with if($route->current() != null) on line 373 the error goes away but i am not sure is it the correct way or not.

**Comment by antonioribeiro** [comment]
I'm not sure you're talking about the same problem, but https://github.com/antonioribeiro/tracker/commit/f48c76fba81c7c142e7a4945942104dc5390e697 is fixing current route == null.

And, no, I don't think route path can be stored as null.

**Comment by joy014** [comment]
Yes. Problem solved. Thanks for the prompt response. Thanks a ton.

**Comment by antonioribeiro** [comment]
Cool! Thanh you!
