### ISSUE TITLE
Laravel 5 issues

### ISSUE THREAD

**Issue by gerob** [antonioribeiro/tracker#64]
Hi Antonio, great package you've made here. It worked quite well for me in Laravel 4. In Laravel 5 I am having a bit of issue getting it working completely. Specifically the views are not able to be found by Laravel.

Everything work up until the controller tries to load the views. Then it tells me that the hint path for pragmarx/tracker doesn't exist. Am I missing something?

The other thing that I thought may be related is when I `vendor:publish` I get the error:

```
Can't locate path: </home/vagrant/sites/geroblee/vendor/pragmarx/tracker/src/Vendor/Laravel/../../migrations>
```

**Comment by antonioribeiro** [comment]
Hey Gerob!

Yeah, L5 Tracker is still a WIP, because I'm in the process to convert a pretty big app to Laravel 5, just to make sure everything goes smooth. That's why I didn't tagged a version for it, yet. As soon as I make some progress on it I'll let you know, so I'll leave this one opened.

Thank you!

**Comment by antonioribeiro** [comment]
The `vendor:publish` publish problem was fixed by https://github.com/antonioribeiro/support/commit/e4bda7e4ea945b035b77d8d60364b9bb01956d66.

**Comment by antonioribeiro** [comment]
Now @gerob what views are you talking about exactly? Your app views or Tracker (stats) views?

**Comment by gerob** [comment]
Hey Antonio, the tracker views could not be found, I believe this requires
registering them with loadViewFiles.

**Comment by antonioribeiro** [comment]
Should be fixed now.

**Comment by gerob** [comment]
Awesome thanks! I will test tonight and report back. :+1:

**Comment by gerob** [comment]
Hey Antonio, finally got a chance to do some testing again. I installed it to a fresh L5 install, and followed the steps to install.

Everything works until after this step https://github.com/antonioribeiro/tracker#enable-tracker-in-your-configphp-laravel-4-or-trackerphp-laravel-5

Then I get the following error related to Bllim Datatables.

```
vagrant@homestead:~/sites/datatables$ php artisan tracker:updateparser

  [BadMethodCallException]
  Call to undefined method [package]

```

**Comment by antonioribeiro** [comment]
Datatables fixed: https://github.com/antonioribeiro/tracker/commit/b439c5d6b291abade2316e1b03037c546bcd7e4e.

Sorry about this.

**Comment by gerob** [comment]
Thanks Antonio! Great work. I went through and turned all the tracking features on and everything seems to be recording and outputting properly. No issues that I could find.

Love the switch to Google charts as I was working on something similar utilizing this package https://github.com/kevinkhill/lavacharts. 

Thanks again,
Gerob

**Comment by antonioribeiro** [comment]
Cool! Thanks for the feedback, @gerob! I'll take a look at lavacharts.
