### ISSUE TITLE
Route names are not being saved

### ISSUE THREAD

**Issue by pranshu792** [antonioribeiro/tracker#65]
After some previous commits, somehow route names are not being saved in tracker_routes whereas route_paths are being saved..!

This is my config file..

	 * Which routes names are not trackable?
	 */
	'do_not_track_routes' => [
		'tracker.stats.*', 'api.*'
	],
       

	/**
	 * Do you wish to log devices?
	 */
	'log_devices' => true,

	/**
	 * Do you wish to log HTTP referers?
	 */
	'log_referers' => true,

	/**
	 * Do you wish to log url paths?
	 */
	'log_paths' => true,

	/**
	 * Do you wish to log url queries and query arguments?
	 */
	'log_queries' => true,

	/**
	 * Do you wish to log routes and route parameters?
	 */
	'log_routes' => true,

	/**
	 * Log errors and exceptions?
	 */
	'log_exceptions' => false,

Is there any way so that i can track route names??

**Comment by antonioribeiro** [comment]
I just did a test on master and it's working for me:

```
 $ sqlite3 /tmp/production.sqlite
SQLite version 3.8.2 2013-12-06 14:53:30

sqlite> select * from tracker_routes;
1|home|HomeController@showWelcome|2015-03-04 14:07:38|2015-03-04 14:07:38

sqlite> .schema tracker_routes
CREATE TABLE "tracker_routes" ("id" integer not null primary key autoincrement, "name" varchar not null, "action" varchar not null, "created_at" datetime not null, "updated_at" datetime not null);
```

**Comment by pranshu792** [comment]
Route names problem is not resolved in mysql.
Can you just check a test in mysql platform?

Only a single row is created i.e.
![route](https://cloud.githubusercontent.com/assets/8383179/6662340/6fe7459e-cbe0-11e4-92e8-ae90f69a43d1.PNG)

**Comment by antonioribeiro** [comment]
Works for me

```
mysql> select * from tracker_routes;
+----+------+----------------------------+---------------------+---------------------+
| id | name | action                     | created_at          | updated_at          |
+----+------+----------------------------+---------------------+---------------------+
|  1 | home | HomeController@showWelcome | 2015-03-16 18:13:07 | 2015-03-16 18:13:07 |
+----+------+----------------------------+---------------------+---------------------+
1 row in set (0.00 sec)
```

**Comment by antonioribeiro** [comment]
Using Laravel 4 & MySQL

```
mysql> select * from tracker_routes;
+----+-------------+-------------------------------+---------------------+---------------------+
| id | name        | action                        | created_at          | updated_at          |
+----+-------------+-------------------------------+---------------------+---------------------+
|  1 | home        | HomeController@showWelcome    | 2015-03-16 18:13:07 | 2015-03-16 18:13:07 |
|  2 | welcome     | HomeController@sayWelcome     | 2015-03-16 18:14:47 | 2015-03-16 18:14:47 |
|  3 | coming.soon | HomeController@showComingSoon | 2015-03-16 18:15:15 | 2015-03-16 18:15:15 |
+----+-------------+-------------------------------+---------------------+---------------------+
3 rows in set (0.00 sec)
```

And this one using PostgreSQL in a Laravel 5 app:

![tracker](https://cloud.githubusercontent.com/assets/3182864/6673167/e66fbb10-cbef-11e4-9515-b71ac0559b82.png)
