### ISSUE TITLE
Stats Panel Not Displaying Data

### ISSUE THREAD

**Issue by ian3stacks** [antonioribeiro/tracker#66]
I am using laravel 4.2

I went through the install just fine and there is data in the database tables.

The admin panel is not displaying that data. The only data that shows is views by country.

**Comment by antonioribeiro** [comment]
I noticed something was wrong with this latest sb-admin, every time they do an update, Tracker breaks. Looking into it, thanks.

**Comment by antonioribeiro** [comment]
Should be fixed now, but Bllim/Datatables is (kind of) broken and I'm still having trouble with Events, at least with an empty result set.

**Comment by antonioribeiro** [comment]
Asked a question about it here: https://github.com/bllim/laravel4-datatables-package/issues/202

**Comment by antonioribeiro** [comment]
Should be fixed now.
