### ISSUE TITLE
SQL error when running migration

### ISSUE THREAD

**Issue by OliverShanahan** [antonioribeiro/tracker#67]
Laravel v4.2.17.
Following instructions from https://github.com/antonioribeiro/tracker
When running the migrate command 'php artisan migrate' it fails with the following error

  [Illuminate\Database\QueryException]                                                                                        
  SQLSTATE[HY000]: General error: 1005 Can't create table 'tracker.#sql-2324_20a0' (errno: 150) (SQL: SQLSTATE[HY000]: Gene  
  ral error: 1005 Can't create table 'tracker.#sql-2324_20a0' (errno: 150) (SQL: alter table `tracker_route_paths` add cons  
  traint tracker_route_paths_route_id_foreign foreign key (`route_id`) references `tracker_routes` (`id`) on delete cascade   
  on update cascade)) 

mysql> show engine innodb status;

------------------------
LATEST FOREIGN KEY ERROR
------------------------
150307 14:56:53 Error in foreign key constraint of table tracker/#sql-2324_20a4:
 foreign key (`route_id`) references `tracker_routes` (`id`) on delete cascade on update cascade:
Cannot find an index in the referenced table where the
referenced columns appear as the first columns, or column types
in the table and the referenced table do not match for constraint.
Note that the internal storage type of ENUM and SET changed in
tables created with >= InnoDB-4.1.12, and such columns in old tables
cannot be referenced by such columns in new tables.
See http://dev.mysql.com/doc/refman/5.5/en/innodb-foreign-key-constraints.html
for correct foreign key definition.

**Comment by antonioribeiro** [comment]
This is an example why I can't stand MySQL... 

Well, installed it here and I don't have a clue what's happening, because the referenced table is all right:

```
+------------+---------------------+------+-----+---------------------+----------------+
| Field      | Type                | Null | Key | Default             | Extra          |
+------------+---------------------+------+-----+---------------------+----------------+
| id         | bigint(20) unsigned | NO   | PRI | NULL                | auto_increment |
| name       | varchar(255)        | NO   | MUL | NULL                |                |
| action     | varchar(255)        | NO   | MUL | NULL                |                |
| created_at | timestamp           | NO   | MUL | 0000-00-00 00:00:00 |                |
| updated_at | timestamp           | NO   | MUL | 0000-00-00 00:00:00 |                |
+------------+---------------------+------+-----+---------------------+----------------+
```

As you can see the `id` is the primary key, and, of course, also indexed. So what's the problem again?

**Comment by antonioribeiro** [comment]
Fixed MySQL oddities in https://github.com/antonioribeiro/tracker/commits/v1.0.2
