### ISSUE TITLE
Undefined index: APP_URL

### ISSUE THREAD

**Issue by pranshu792** [antonioribeiro/tracker#70]
Error exception thrown just after composer update

private function getAppUrl()
	{
		// Is it possible to get this via Laravel?
		// $this->app->make('request')->server('APP_URL');
		return $_SERVER['APP_URL'];
	}

**Comment by pranshu792** [comment]
Dump of $_SERVER, no APP_URL found


<pre class='xdebug-var-dump' dir='ltr'>
<b>array</b> <i>(size=36)</i>
  'HTTP_HOST' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'localhost'</font> <i>(length=9)</i>
  'HTTP_CONNECTION' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'keep-alive'</font> <i>(length=10)</i>
  'HTTP_ACCEPT' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'</font> <i>(length=74)</i>
  'HTTP_USER_AGENT' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36'</font> <i>(length=109)</i>
  'HTTP_ACCEPT_ENCODING' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'gzip, deflate, sdch'</font> <i>(length=19)</i>
  'HTTP_ACCEPT_LANGUAGE' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'en-US,en;q=0.8'</font> <i>(length=14)</i>
  'HTTP_COOKIE' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'mp_f467200c023b16646361bd1e267ef809_mixpanel=%7B%22distinct_id%22%3A%20%223%22%2C%22__mps%22%3A%20%7B%7D%2C%22__mpso%22%3A%20%7B%7D%2C%22__mpa%22%3A%20%7B%22pageviews%22%3A%20375%7D%2C%22__mpap%22%3A%20%5B%5D%2C%22%24initial_referrer%22%3A%20%22http%3A%2F%2Flocalhost%2Flms%2Findex.php%2Fanalytics%2Fuser%22%2C%22%24initial_referring_domain%22%3A%20%22localhost%22%7D; mp_a16b048a400b875fcf6cdf02e9429875_mixpanel=%7B%22distinct_id%22%3A%20%22anon%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24init'...</font> <i>(length=1072)</i>
  'PATH' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'C:\ImageMagick;C:\Program Files (x86)\ImageMagick-6.9.0-Q16;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\wamp\bin\php\php5.5.12;C:\ProgramData\ComposerSetup\bin;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Bitvise SSH Client;C:\Program Files\nodejs\;C:\Program Fil'...</font> <i>(length=541)</i>
  'SystemRoot' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'C:\Windows'</font> <i>(length=10)</i>
  'COMSPEC' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'C:\Windows\system32\cmd.exe'</font> <i>(length=27)</i>
  'PATHEXT' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC'</font> <i>(length=53)</i>
  'WINDIR' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'C:\Windows'</font> <i>(length=10)</i>
  'SERVER_SIGNATURE' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'&lt;address&gt;Apache/2.4.9 (Win64) PHP/5.5.12 Server at localhost Port 80&lt;/address&gt;&#10;'</font> <i>(length=79)</i>
  'SERVER_SOFTWARE' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'Apache/2.4.9 (Win64) PHP/5.5.12'</font> <i>(length=31)</i>
  'SERVER_NAME' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'localhost'</font> <i>(length=9)</i>
  'SERVER_ADDR' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'::1'</font> <i>(length=3)</i>
  'SERVER_PORT' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'80'</font> <i>(length=2)</i>
  'REMOTE_ADDR' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'::1'</font> <i>(length=3)</i>
  'DOCUMENT_ROOT' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'C:/wamp/www/'</font> <i>(length=12)</i>
  'REQUEST_SCHEME' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'http'</font> <i>(length=4)</i>
  'CONTEXT_PREFIX' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>''</font> <i>(length=0)</i>
  'CONTEXT_DOCUMENT_ROOT' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'C:/wamp/www/'</font> <i>(length=12)</i>
  'SERVER_ADMIN' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'admin@example.com'</font> <i>(length=17)</i>
  'SCRIPT_FILENAME' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'C:/wamp/www/lms/index.php'</font> <i>(length=25)</i>
  'REMOTE_PORT' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'64074'</font> <i>(length=5)</i>
  'GATEWAY_INTERFACE' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'CGI/1.1'</font> <i>(length=7)</i>
  'SERVER_PROTOCOL' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'HTTP/1.1'</font> <i>(length=8)</i>
  'REQUEST_METHOD' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'GET'</font> <i>(length=3)</i>
  'QUERY_STRING' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>''</font> <i>(length=0)</i>
  'REQUEST_URI' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'/lms/index.php/'</font> <i>(length=15)</i>
  'SCRIPT_NAME' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'/lms/index.php'</font> <i>(length=14)</i>
  'PATH_INFO' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'/'</font> <i>(length=1)</i>
  'PATH_TRANSLATED' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'C:\wamp\www\index.php'</font> <i>(length=21)</i>
  'PHP_SELF' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'/lms/index.php/'</font> <i>(length=15)</i>
  'REQUEST_TIME_FLOAT' <font color='#888a85'>=&gt;</font> <small>float</small> <font color='#f57900'>1426434874.133</font>
  'REQUEST_TIME' <font color='#888a85'>=&gt;</font> <small>int</small> <font color='#4e9a06'>1426434874</font>
</pre>

**Comment by antonioribeiro** [comment]
Yeah, I'm still a bit unsure of how I would get the current url to pass to the new referer parser, that's why I didn't tagged a version yet.

**Comment by antonioribeiro** [comment]
Looks like APP_URL is present in my $_SERVER but not yours, I don't know where this key came from but it would be handy :)

**Comment by antonioribeiro** [comment]
Of course it isn't, and of course I'm dumb, that var was loaded by dotenv!!!! :D

**Comment by antonioribeiro** [comment]
Should be fixed now. Thank you!

**Comment by pranshu792** [comment]
Ok.. Anytime
