### ISSUE TITLE
Cannot add foreign key constraint

### ISSUE THREAD

**Issue by pranshu792** [antonioribeiro/tracker#71]
SQL Error showing up when database is migrated..! 

[Illuminate\Database\QueryException]
  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL
  : SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (S
  QL: alter table `tracker_referers_search_terms` add constraint tracker_refe
  rers_referer_id_fk foreign key (`referer_id`) references `tracker_referers`
   (`id`) on delete cascade on update cascade))

  [PDOException]
  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint

migrate [--bench[="..."]] [--database[="..."]] [--force] [--path[="..."]] [--pac
kage[="..."]] [--pretend] [--seed]

**Comment by antonioribeiro** [comment]
Should be fixed now. Thank you!
