### ISSUE TITLE
Separate Admin UI from main package

### ISSUE THREAD

**Issue by NoelDavies** [antonioribeiro/tracker#73]
I was wondering if we could separate the ui from the main package as I'm trying to use the package into a L4.2 platform and it's causing me all sort of troubles because of the "stats-panel" stuff.

It'd also mean the tracker-ui could have the main tracker package as a dependency so that wouldn't break it.

I could do this in my own fork but I think it'd be beneficial to more people than just me.

**Comment by antonioribeiro** [comment]
You could do this on your own fork and Pull Request it! :P

Yeah, I like the idea of not having the UI coupled to the main package and might do something like that at some point.

But could you tell me what problems you are having in 4.2? If you turn off `stats_panel_enabled` it is supposed to not try to create routes, but looks like that's not what's happening to you...

**Comment by NoelDavies** [comment]
it was issues with the routes. It's okay I just did an override with the service provider, didn't manage to get a fix in >.< 

![Img](http://i.imgur.com/kS7FR6e.png) This is what I have so far.

**Comment by oryxgd** [comment]
@NoelDavies love the UI you built out of it. Any chance you have open sourced it? Or is it based on a package already?

**Comment by NoelDavies** [comment]
@oryxgd sadly not, It's for a SaaS platform for a client I as working with. I can't release the code but can help you achieve something similar?

**Comment by zeeshan-za-ahmad** [comment]
can u tell me what routes i have to use to show gui in browser in laravel 5.2.
i've done this https://github.com/antonioribeiro/tracker#stats-panel .but dont know how to access this in browser.
as i m beginner please help me to sort out this.
