### ISSUE TITLE
Custom tracking

### ISSUE THREAD

**Issue by peter-mw** [antonioribeiro/tracker#75]
Hi,

Very nice package

I am trying to integrate it into my CMS 

Is there a way to track things that are not in the config file?

I want to track things that have dynamic routes and events. 

Is there some way to directly call the tracking functions? 

Something like `Tracker::trackEvent('cart.add',$data)` 
or i want to track page view with something like `Tracker::trackVisit('my/dynamic/url')`

Are there some methods like that and a way to call them on runtime?

**Comment by antonioribeiro** [comment]
If you don't use real events (Event::fire()) and requests for (visits), you may end up with a database full of things that didn't really happened in your application, don't you think?

Could you tell me more, and give pratical examples, about those "dynamic routes"? Maybe that's something I should take care and automatically store via Tracker...

**Comment by peter-mw** [comment]
Hi, thanks for your answers

For the dynamic routes, i have a "catch-all" route that generates a page via default controller, if existing route is not found.  

In my case, if someone goes to domain.com/some-post-title the "some-post-title" page is served by the catch-all route and doesn't have a defined route. 

In the my case i want to be able to track custom things. Either trough events or some other way. The problem with events is that i don't know their exact names. They may be added by some external module and are "dynamic", so i cant hard code them in https://github.com/antonioribeiro/tracker/blob/master/src/config/config.php#L106

**Comment by antonioribeiro** [comment]
Got it, a catch all route may really be a problem... :(

And yes, if you leave that array empty it will track every single event, except those present in the `do_not_log_events` array.

**Comment by peter-mw** [comment]
Maybe if i call this method directly https://github.com/antonioribeiro/tracker/blob/master/src/Tracker.php#L62 it will do the trick

**Comment by antonioribeiro** [comment]
That will not work. Things are tracked differently. For instance, the route is tracked by a hook in the event 'router.matched', because you have no access to the route information until the application reaches the routing system. So I log almost everything, except for route, events, exceptions and sql queries way before the aplication is completelly booted.

**Comment by antonioribeiro** [comment]
Just pushed `Tracker::trackEvent()` and it should available on dev-master.

**Comment by peter-mw** [comment]
Great! Thank you a lot!

Will download now and continue playing

**Comment by antonioribeiro** [comment]
I'm working on a manual route tracking, which is a little more complicated than event :)

**Comment by antonioribeiro** [comment]
`Tracker::trackVisit()` also pushed, take a look at the readme to see the parameters.

**Comment by peter-mw** [comment]
Cool!! 

Man you are the best!! 

I will take a look and report if i find issues

I owe you many beers :) 

Thanks for adding those methods and hope others find them useful too.

Cheers :)

**Comment by antonioribeiro** [comment]
No problem! Enjoy it!
