### ISSUE TITLE
Current Session/Visitor example

### ISSUE THREAD

**Issue by goeroe** [antonioribeiro/tracker#77]
I get the following error when trying your example

"$visitor = Tracker::currentSession();"

Non-static method PragmaRX\Tracker\Tracker::currentSession() should not be called statically, assuming $this from incompatible context

**Comment by antonioribeiro** [comment]
You cannot use the class directly this way, you have to use the Facade:

```
use PragmaRX\Tracker\Vendor\Laravel\Facade as Tracker;

Tracker::currentSession();
```

But in Laravel you better add the Facade to your app.php:

```
'Tracker' => 'PragmaRX\Tracker\Vendor\Laravel\Facade',
```

And just

```
use Tracker;

Tracker::currentSession();
```
