### ISSUE TITLE
L4 tracker:tables not working

### ISSUE THREAD

**Issue by Prophet731** [antonioribeiro/tracker#78]
When attempting to run `php artisan tracker:tables` I get this error. I have added both the alias and provider.

```
$ php artisan tracker:tables



  [InvalidArgumentException]
  There are no commands defined in the "tracker" namespace.

```

**Comment by JanFoerste** [comment]
I had the same problem at first. Did you publish the config and set 'enabled' => true ?

**Comment by Prophet731** [comment]
Yes, configs were published and it was enabled. The command doesn't seem to register with Artisan though.

**Comment by antonioribeiro** [comment]
If this is still valid, please ask to reopen.
