### ISSUE TITLE
"Tracker: uaparser regex file not available"

### ISSUE THREAD

**Issue by JanFoerste** [antonioribeiro/tracker#79]
Hi,

I just installed the tracker on both, my local development environment as well as our main production server. It seems to work just fine locally (a Windows machine running Apache) but doesn't work on the server (Debian Wheezy, nginx, php-fpm). Whenever the application loads, The following error will be logged: "Tracker: uaparser regex file not available. "Execute php artisan tracker:updateparser" to generate it.". Obviously, I tried running that command multiple times, which always seemed to succeed, but the error will still be logged. The permissions to the required regex file are set to 770 and it's owned by www-data (777 permissions don't change anything). This seems to block any tracking whatsoever as I don't get any logs.

**Comment by zawzawzaw** [comment]
I also have the same problem here, 
"production.ERROR: Tracker: uaparser regex file not available. "Execute php artisan tracker:updateparser" to generate it. [] []"
also tried to execute the command in the error error didn't seems to goes away.

**Comment by antonioribeiro** [comment]
Change the way this is done. Should be fixed.
