### ISSUE TITLE
User model not found

### ISSUE THREAD

**Issue by JanFoerste** [antonioribeiro/tracker#80]
To track users, I set the user model to mine (\User). This works fine on my local development environment but not on the exact mirror on our production server. It keeps logging an "Trying to get property of non-object" error on PragmaRX\Tracker\Tracker->checkCurrentUser(), ->getSessionData(). ->getDeviceId() and PragmaRX\Tracker\Data\RepositoryManager->getCurrentDeviceProperties().

**Comment by thiagof** [comment]
Your local env may not be getting stats.. Check the `config('tracker.do_not_track_ips')`

But your error I think is due to an undocumented step.
Try after running

    php artisan tracker:updateparser

**Comment by Namoshek** [comment]
Thanks for your hint, updating the parser solved the problem for me. Now let's check out that baby. :)
