### ISSUE TITLE
Doesn't save any data to database 

### ISSUE THREAD

**Issue by kiran-subedi34** [antonioribeiro/tracker#83]
Hey Antonio,
You have build awesome package.Thanks for providing Us. I am new in laravel. I had tried to use this. I have set up this package as that you have provided in your documentation. I am little bit confused. 
Do I really need to make different database to track the visitor ?
Can't I use on my default database?

When I tried as you described like
$visitor = Tracker::currentSession();
var_dump( $visitor->client_ip );
var_dump( $visitor->device->is_mobile );
var_dump( $visitor->device->platform );
var_dump( $visitor->geoIp->city );

I get the following error 
Trying to get property of non-object

Then I checked on database. Nothing was stored on the database but on tracker_errors above error was store.

Sorry for the bad English

**Comment by zawzawzaw** [comment]
same for me here I did enabled log option in config and I think its suppose to start tracking but it doesn't seems to all my table are empty still.

**Comment by zawzawzaw** [comment]
after I run php artisan tracker:updateparser, TWICE in it seems to start tracking the data and also removed the error that I'm getting "production.ERROR: Tracker: uaparser regex file not available. "Execute php artisan tracker:updateparser" to generate it."

**Comment by antonioribeiro** [comment]
Seems those problems are not happening to most of us. If it's still happening, please ask to reopen.

**Comment by m7vm7v** [comment]
[Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "tracker:updateparser" is not defined.
  Did you mean this?
      tracker:tables

Any ideas how to execute the command?
