### ISSUE TITLE
do_not_track_routes working?

### ISSUE THREAD

**Issue by Deivide** [antonioribeiro/tracker#85]
do_not_track_routes track routes if:
```php
'log_enabled' => true,
```
?

I need to lock the track in admin.* routes, but it is not working.

```php
'do_not_track_routes' => [
		'tracker.stats.*',
		'admin.*',
	],
```

**Comment by antonioribeiro** [comment]
Works for me. If it still doesn't work for you, please ask to reopen.

**Comment by ahmadbadpey** [comment]
it does not work for me too?
how to solve it?
