### ISSUE TITLE
tracker doesn't work at all.

### ISSUE THREAD

**Issue by mrsadrzadeh** [antonioribeiro/tracker#86]
I get this message when enabling some logs including 'log_user_agents', 'log_user', 'log_devices'
"Trying to get property of non-object"
and other logs just return null

**Comment by gabrielkoerich** [comment]
Same problem here: https://www.dropbox.com/s/7829ye3bcv2y82w/Screenshot%202015-05-04%2000.40.52.png?dl=0

**Comment by esseremmerik** [comment]
Same for me, any suggestions @antonioribeiro?

**Comment by lucidlemon** [comment]
have you executed
`php artisan tracker:updateparser`
after installing everything? It logged a few thousand errors of this into my log files, after executing this command, everything worked

**Comment by destroyer998** [comment]
@lucidlemon, thanks worked for me!
