### ISSUE TITLE
[Reopen] Same uuid for different user of same device

### ISSUE THREAD

**Issue by gaupoit** [antonioribeiro/tracker#89]
I pulled the newest version (2.0@dev) however I still meet the same issue (https://github.com/antonioribeiro/tracker/issues/72). Need ur help guys. Thanks.

**Comment by gaupoit** [comment]
So I modified the Session.php repository:  
private function sessionIsReliable()
    {
        $data = $this->getSessionData();

        return  $data['user_id'] === $this->sessionInfo['user_id'] &&
                isset($data['client_ip']) &&
                $data['client_ip'] === $this->sessionInfo['client_ip'] &&

                isset($data['user_agent']) &&
                $data['user_agent'] === $this->sessionInfo['user_agent'];
    }

**Comment by antonioribeiro** [comment]
Could you explain what you did? Looks like you removed one single line...

Please ask for reopening in case you still want to help me fix this.
