### ISSUE TITLE
Date Between

### ISSUE THREAD

**Issue by erayaydin** [antonioribeiro/tracker#96]
Are there any way for getting sessions/users/pageViews for between 2 date?

with **Eloquent** I can do that but I think it should be available with `Tracker::pageViews(60 * 24 * 30, $startDate);`

**Comment by rustem-art** [comment]
I'm too not understand, how i can request session' periods by date?
Can any help me, or show some example?

**Comment by antonioribeiro** [comment]
It's undocumented, I know, but those methods accept a Minutes object, which already is a datetime range, so you'll be able to do:

    $range = new Minutes();

    $range->setStart(Carbon::now()->subDays(2));

    $range->setEnd(Carbon::now()->subDays(1));

    Tracker::pageViews($range);
