### ISSUE TITLE
Can't track custom events

### ISSUE THREAD

**Issue by emergingdzns** [antonioribeiro/tracker#97]
I've installed the tracker library and have it doing the default tracking just fine. That part is all good.
However, I tried to add in a custom event tracker to log some events we need data on.

So, in my code I've added:
```
Tracker::trackEvent(['name' => 'Event Name', 'object' => [{ my data in an array }]);
```
Initially, I get the following error:
```
 ErrorException
…/­vendor/­pragmarx/­tracker/­src/­Data/­Repositories/­Event.php174
...
172  private function getEventId($event)
173 {
174  	return $event['event']
175  		?   $this->findOrCreate(
176				array('name' => $event['event']),
...
```
What I'm not understanding is that in the instructions it says to use an array with keys 'name' and 'object'. Yet the Event.php seems to be looking for an 'event' key. And if the event key doesn't exist it doesn't create an object.

Nothing is showing in the database. I added @ in front of the $event in line 174, but now nothing happens except for the standard stats logging.

I could really use some guidance here.

**Comment by clin407** [comment]
send as this:

Tracker::trackEvent(['event' => 'Event Name', 'object' => [{ my data in an array }]);

it should work then.
