### ISSUE TITLE
Error when log_enabled = true

### ISSUE THREAD

**Issue by clin407** [antonioribeiro/tracker#98]
I'm having an issue when I have every single thing logged (in config it's the 'log_enabled' key). When I set it to true, I get the below error when trying to access the stats page:

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`database`.`tracker_events_log`, CONSTRAINT `tracker_events_log_log_id_foreign` FOREIGN KEY (`log_id`) REFERENCES `tracker_log` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) (SQL: insert into `tracker_events_log` (`log_id`, `event_id`, `class_id`, `updated_at`, `created_at`) values (2, 4, 2, 2015-07-07 23:19:25, 2015-07-07 23:19:25))

When I set it to false, everything else works fine. Any ideas what's going on? is the events log being inserted before the tracker log?

I'm currently on dev-master 3f81929 since I wanted to take advantage of the trackEvent method.

**Comment by nuukcillo** [comment]
I have the same problem, when I enable this function the application stops working.

**Comment by nuukcillo** [comment]
I fixed this thing changing this configuration, I have the panel on stats route.
```
'do_not_track_routes' => [
-		'tracker.stats.*',
+		'stats.*',
 	],
```

**Comment by anhdt1987vn** [comment]
@nuukcillo :+1:  same problems, 
thanks

**Comment by antonioribeiro** [comment]
Fixed.
